package com.yqg.drools.model.base;

import lombok.Getter;

/*****
 * @Author zengxiangcai
 * created at ${date}
 * @email zengxiangcai@yishufu.com
 ****/

@Getter
public enum RuleEnum {
    LATEST_LOAN_OVERDUE_DAYS("LATEST_LOAN_OVERDUE_DAYS"),
    CONTACT_SENSITIVE_WORD_COUNT("CONTACT_SENSITIVE_WORD_COUNT"),
    CONTACT_MOBILE_COUNT("CONTACT_MOBILE_COUNT"),
    CONTACT_INTERRELATED_WORD_COUNT("CONTACT_INTERRELATED_WORD_COUNT"),
    CONTACT_OWNER_MOBILE_OVERDUE30_COUNT("CONTACT_OWNER_MOBILE_OVERDUE30_COUNT"),
    CONTACT_MOBILE_OVERDUE30_COUNT("CONTACT_MOBILE_OVERDUE30_COUNT"),
    CALL_INFO_MOBILE_OVERDUE30_COUNT("CALL_INFO_MOBILE_OVERDUE30_COUNT"),
    CALL_INFO_LATEST_CALL_DIFF_DAY("CALL_INFO_LATEST_CALL_DIFF_DAY"),
    CALL_INFO_ACTIVE_AT_EVENING("CALL_INFO_ACTIVE_AT_EVENING"),
    SHORT_MESSAGE_OVERDUE_WORDS("SHORT_MESSAGE_OVERDUE_WORDS"),
    SHORT_MESSAGE_NEGATIVE_WORDS("SHORT_MESSAGE_NEGATIVE_WORDS"),
    SHORT_MESSAGE_INTERRELATED_WORDS("SHORT_MESSAGE_INTERRELATED_WORDS"),
    SHORT_MESSAGE_CALLEE_OVERDUE15_COUNT("SHORT_MESSAGE_CALLEE_OVERDUE15_COUNT"),
    SHORT_MESSAGE_RECENT30DAY_REJECT_COUNT("SHORT_MESSAGE_RECENT30DAY_REJECT_COUNT"),
    SHORT_MESSAGE_RECENT30DAY_OVERDUE_COUNT("SHORT_MESSAGE_RECENT30DAY_OVERDUE_COUNT"),
    SHORT_MESSAGE_RECENT30DAY_DISTINCT_OVERDUE_COUNT("SHORT_MESSAGE_RECENT30DAY_DISTINCT_OVERDUE_COUNT"),
    SHORT_MESSAGE_RECENT15DAY_MSG_COUNT("SHORT_MESSAGE_RECENT15DAY_MSG_COUNT"),
    INSTALLED_APP_LOAN_APP_COUNT("INSTALLED_APP_LOAN_APP_COUNT"),
    INSTALLED_APP_LOAN_APP_RATIO("INSTALLED_APP_LOAN_APP_RATIO"),
    INSTALLED_APP_LOAN_APP_INCREMENT("INSTALLED_APP_LOAN_APP_INCREMENT"),
    INSTALLED_APP_LOAN_APP_RATIO_CHANGE("INSTALLED_APP_LOAN_APP_RATIO_CHANGE"),
    EMPTY_CONTACT_INFO("EMPTY_CONTACT_INFO"),
    EMPTY_SHORT_MESSAGE("EMPTY_SHORT_MESSAGE");

    RuleEnum(String name){
        this.ruleName = name;
    }
    private String ruleName;

}
