package com.yqg.common.enums.order;

/**
 * @author niebiafei
 */
public enum BlackListTypeEnum {

    DATA_EMPTY(-1, "DATA_EMPTY"), // 数据为空
    AGE_UP(1, "AGE_UP"),  // 年龄高于限定值
    AGE_UP_MALE(1,"AGE_UP_MALE"),
    AGE_UP_FEMALE(1,"AGE_UP_FEMALE"),
    AGE_LOW(2, "AGE_LOW"), // 年龄低于限定值
    YITU_SCORE_LIMIT(3, "YITU_SCORE_LIMIT"), // 依图人脸识别相似度
    CONTACT_COUNT(4, "CONTACT_COUNT"),    // 通讯录个数（去重）
    CONTACT_SENSITIVI_COUNT(5, "CONTACT_SENSITIVI_COUNT"), // 通讯录敏感词个数
    CONTACT_SAME_PRODUCT_COUNT(6, "CONTACT_SAME_PRODUCT_COUNT"), // 通讯录同行业个数
    CONTACT_RELATIVE_COUNT(7, "CONTACT_RELATIVE_COUNT"), // 通讯录亲属称谓个数
    PHONE_USED_DAY(8, "PHONE_USED_DAY"), // 手机使用时长（单位：天）
    USER_INSTALLED_SENSITIVE_APP_COUNT(9, "USER_INSTALLED_SENSITIVE_APP_COUNT"), // 用户安装了敏感app个数
    USER_INSTALLED_SENSITIVE_APP_PERSENT(10, "USER_INSTALLED_SENSITIVE_APP_PERSENT"), // 用户安装了敏感app比率
    USER_DEVICE_ID(11, "USER_DEVICE_ID"), // 用户deviceId 存在目前的deviceId列表中个数
    FIRST_CONTACT_NOT_EXIST_RELATIVES(12, "FIRST_CONTACT_NOT_EXIST_RELATIVES"), //第一联系人不在通讯录
    SECOND_CONTACT_NOT_EXIST_RELATIVES(13, "SECOND_CONTACT_NOT_EXIST_RELATIVES"), //第二联系人不在通讯录
    ADDRESS_INVALID(14, "ADDRESS_INVALID"), //地址不在指定区域
    COMPANY_TEL_NOT_IN_JAKARTA(15, "COMPANY_TEL_NOT_IN_JAKARTA"), //公司电话不是大雅加达区号开头
    DEVICE_ID_IN_BLACK_LIST(16, "DEVICE_ID_IN_BLACK_LIST"), //申请手机号命中摇钱罐device_id黑名单
    MOBILE_LANGUAGE(17, "MOBILE_LANGUAGE"), // 手机系统语言
    IP_ADDRESS_COUNT(18, "IP_ADDRESS_COUNT"), // 同一天内同一个IP的申请次数
    IP_ADDRESS_COUNT_REMARK(18, "IP_ADDRESS_COUNT_REMARK"), // 同一天内同一个IP的申请次数-标签

    LIVE_ADDRESS_INVALID(19, "LIVE_ADDRESS_INVALID"), // 居住地址不在指定区域
    WORK_ADDRESS_INVALID(20, "WORK_ADDRESS_INVALID"), // 工作地址不在指定区域
    SCHOOL_ADDRESS_INVALID(21, "SCHOOL_ADDRESS_INVALID"), // 学校地址不在指定区域
    ORDER_ADDRESS_INVALID(22, "ORDER_ADDRESS_INVALID"), // 下单不在指定区域

    SMS_OVERDUE_COUNT(101, "SMS_OVERDUE_COUNT"), // 短信逾期词个数
    SMS_NEGATIVE_COUNT(102, "SMS_NEGATIVE_COUNT"), // 短信负面词个数
    SMS_SAME_COUNT(103, "SMS_SAME_COUNT"), // 短信同业词个数
    SMS_ALL_COUNT(104, "SMS_ALL_COUNT"), // 短信总条数
    SMS_NINETY_COUNT(105, "SMS_NINETY_COUNT"), // 短信90天条数
    SMS_THIRTY_COUNT(106, "SMS_THIRTY_COUNT"), // 短信30天条数
    SMS_LONG_DAY_COUNT(107, "SMS_LONG_DAY_COUNT"), // 短信最长天数
    SMS_REFUSE_COUNT(108, "SMS_REFUSE_COUNT"), // 近30天被拒绝的条数
    //SMS_OVERDUE_COUNT_THIRTY_DAY(109, "SMS_OVERDUE_COUNT_THIRTY_DAY"), // 近30天逾期短信条数（按号码去重）
    SMS_RECENT30_OVERDUE_DISTINCT_COUNT(109,"SMS_RECENT30_OVERDUE_DISTINCT_COUNT"),

    SMS_OVERDUE_COUNT_NINETY_DAY(110, "SMS_OVERDUE_COUNT_NINETY_DAY"), // 近90天逾期短信条数（按号码去重）
    SMS_TELE_COUNT_THIRTY_DAY(111, "SMS_TELE_COUNT_THIRTY_DAY"), // 近30天手机号码的短信条数
    SMS_TELE_COUNT_NINETY_DAY(112, "SMS_TELE_COUNT_NINETY_DAY"), // 近90天手机号码的短信条数

    SMS_OVERDUE_MORETHAN_15DAYS_COUNT(113, "SMS_OVERDUE_MORETHAN_15DAYS_COUNT"), // 命中逾期大于15天的短信条数
    SMS_OVERDUE_LESSTHAN_15DAYS_COUNT(114,"SMS_OVERDUE_LESSTHAN_15DAYS_COUNT"),//短信出现逾期10-15（含）天的平台个数
    SMS_OVERDUE_LESSTHAN_15DAYS_COUNT_MALE(114, "SMS_OVERDUE_LESSTHAN_15DAYS_COUNT_MALE"), // 短信出现逾期10-15（含）天的平台个数&男
    SMS_OVERDUE_LESSTHAN_15DAYS_COUNT_FEMALE(114, "SMS_OVERDUE_LESSTHAN_15DAYS_COUNT_FEMALE"), // 短信出现逾期10-15（含）天的平台个数&女
    SMS_OVERDUE_MAX_DAYS(115, "SMS_OVERDUE_MAX_DAYS"), // 短信中出现的最大逾期天数

    RECENT_180_CALL_COUNT(201, "RECENT_180_CALL_COUNT"), // 近180天成功 通话次数
    RECENT_90_CALL_COUNT(202, "RECENT_90_CALL_COUNT"), // 近90天成功 通话次数
    RECENT_30_CALL_COUNT(203, "RECENT_30_CALL_COUNT"), // 近30天成功 通话次数
    RECENT_180_CALL_TIME(204, "RECENT_180_CALL_TIME"), // 近180天成功 通话时长
    RECENT_90_CALL_TIME(205, "RECENT_90_CALL_TIME"), // 近90天成功 通话时长
    RECENT_30_CALL_TIME(206, "RECENT_30_CALL_TIME"), // 近30天成功 通话时长
    RECENT_30_CALL_TIME_MALE(206, "RECENT_30_CALL_TIME_MALE"), // 近30天成功 通话时长
    RECENT_180_CALL_IN_COUNT(207, "RECENT_180_CALL_IN_COUNT"), // 近180天成功 打入次数
    RECENT_90_CALL_IN_COUNT(208, "RECENT_90_CALL_IN_COUNT"), // 近90天成功 打入次数
    RECENT_30_CALL_IN_COUNT(209, "RECENT_30_CALL_IN_COUNT"), // 近30天成功 打入次数
    RECENT_180_CALL_IN_TIME(210, "RECENT_180_CALL_IN_TIME"), // 近180天成功 打入时长
    RECENT_90_CALL_IN_TIME(211, "RECENT_90_CALL_IN_TIME"), // 近90天成功 打入时长
    RECENT_30_CALL_IN_TIME(212, "RECENT_30_CALL_IN_TIME"), // 近30天成功 打入时长
    RECENT_180_CALL_OUT_COUNT(213, "RECENT_180_CALL_OUT_COUNT"), // 近180天成功 打出次数
    RECENT_90_CALL_OUT_COUNT(214, "RECENT_90_CALL_OUT_COUNT"), // 近90天成功 打出次数
    RECENT_30_CALL_OUT_COUNT(215, "RECENT_30_CALL_OUT_COUNT"), // 近30天成功 打出次数
    RECENT_180_CALL_OUT_TIME(216, "RECENT_180_CALL_OUT_TIME"), // 近180天成功 打出时长
    RECENT_90_CALL_OUT_TIME(217, "RECENT_90_CALL_OUT_TIME"), // 近90天成功 打出时长
    RECENT_30_CALL_OUT_TIME(218, "RECENT_30_CALL_OUT_TIME"), // 近30天成功 打出时长

    RECENT_180_FIRST_CONTACT_CALL_COUNT(219, "RECENT_180_FIRST_CONTACT_CALL_COUNT"), // 近180天成功 第一联系人 通话次数
    RECENT_90_FIRST_CONTACT_CALL_COUNT(220, "RECENT_90_FIRST_CONTACT_CALL_COUNT"), // 近90天成功 第一联系人 通话次数
    RECENT_30_FIRST_CONTACT_CALL_COUNT(221, "RECENT_30_FIRST_CONTACT_CALL_COUNT"), // 近30天成功 第一联系人 通话次数
    RECENT_180_FIRST_CONTACT_CALL_TIME(222, "RECENT_180_FIRST_CONTACT_CALL_TIME"), // 近180天成功 第一联系人 通话时长
    RECENT_90_FIRST_CONTACT_CALL_TIME(223, "RECENT_90_FIRST_CONTACT_CALL_TIME"), // 近90天成功 第一联系人 通话时长
    RECENT_30_FIRST_CONTACT_CALL_TIME(224, "RECENT_30_FIRST_CONTACT_CALL_TIME"), // 近30天成功 第一联系人 通话时长

    RECENT_180_SECD_CONTACT_CALL_TIME(225, "RECENT_180_SECD_CONTACT_CALL_TIME"), // 近180天成功 第二联系人 累计通话时长
    RECENT_90_SECD_CONTACT_CALL_TIME(226, "RECENT_90_SECD_CONTACT_CALL_TIME"), // 近90天成功 第二联系人 累计通话时长
    RECENT_30_SECD_CONTACT_CALL_TIME(227, "RECENT_30_SECD_CONTACT_CALL_TIME"), // 近30天成功 第二联系人 累计通话时长
    RECENT_180_SECD_CONTACT_CALL_COUNT(228, "RECENT_180_SECD_CONTACT_CALL_COUNT"), // 近180天成功 第二联系人 累计通话次数
    RECENT_90_SECD_CONTACT_CALL_COUNT(229, "RECENT_90_SECD_CONTACT_CALL_COUNT"), // 近90天成功 第二联系人 累计通话次数
    RECENT_30_SECD_CONTACT_CALL_COUNT(230, "RECENT_30_SECD_CONTACT_CALL_COUNT"), // 近30天成功 第二联系人 累计通话次数

    FIRST_CONTACT_LAST_TIME(232, "FIRST_CONTACT_LAST_TIME"),// 最后一次跟第一联系人有效通话时间距提交申请的天数
    SECOND_CONTACT_LAST_TIME(233, "SECOND_CONTACT_LAST_TIME"),// 最后一次跟第二联系人有效通话时间距提交申请的天数
    CONTACT_LAST_TIME(234, "CONTACT_LAST_TIME"),// 最后一次通话距提交订单日期的天数（单位：天）
    CALL_90_IN_RATE(235, "CALL_90_IN_RATE"),// 近90天呼入占比
    CALL_90_OUT_RATE(236, "CALL_90_OUT_RATE"),// 近90天呼出占比
    CALL_30_IN_RATE(237, "CALL_30_IN_RATE"),// 近30天呼入占比
    CALL_30_OUT_RATE(238, "CALL_30_OUT_RATE"),// 近30天呼出占比

    RECENT_180_CALL_NO_CONNECT_COUNT(239, "RECENT_180_CALL_NO_CONNECT_COUNT"),// 近180天 未接通呼入次数
    RECENT_90_CALL_NO_CONNECT_COUNT(240, "RECENT_90_CALL_NO_CONNECT_COUNT"),// 近90天 未接通呼入次数
    RECENT_30_CALL_NO_CONNECT_COUNT(241, "RECENT_30_CALL_NO_CONNECT_COUNT"),// 近30天 未接通呼入次数
    RECENT_180_CALL_NO_CONNECT_RATE(242, "RECENT_180_CALL_NO_CONNECT_RATE"),// 近180天 未接通呼入占比
    RECENT_90_CALL_NO_CONNECT_RATE(243, "RECENT_90_CALL_NO_CONNECT_RATE"),// 近90天 未接通呼入占比
    RECENT_30_CALL_NO_CONNECT_RATE(244, "RECENT_30_CALL_NO_CONNECT_RATE"),// 近30天 未接通呼入占比

    NIGHT_CALL_RATE(245, "NIGHT_CALL_RATE"),// 近30天内夜间活跃占比
    RECENT_180_CALL_RATE(246, "RECENT_180_CALL_RATE"), // 近180天 内未接通电话占比
    RECENT_90_CALL_RATE(247, "RECENT_90_CALL_RATE"),// 近90天 内未接通电话占比
    RECENT_30_CALL_RATE(248, "RECENT_30_CALL_RATE"),// 近30天 内未接通电话占比
    RE_COUNT_NUM(249, "RE_COUNT_NUM"),// 近30天的通话记录中，出现在通讯录中的有效去重通话号码个数
    RE_COUNT_RATE(250, "RE_COUNT_RATE"),// 近30天的通话记录中，出现在通讯录中的有效通话号码个数（去重）占近30天总通话号码的比例（去重）
    RELATIVES_CALL_90_IN_COUNT(251, "RELATIVES_CALL_90_IN_COUNT"),// 近90天 与亲属称谓联系人的通话次数
    RELATIVES_CALL_30_IN_COUNT(252, "RELATIVES_CALL_30_IN_COUNT"),// 近30天 与亲属称谓联系人的通话次数

    RECENT_90_NO_CALL_DAY(253, "RECENT_90_NO_CALL_DAY"),// 近90天 无通话记录总天数
    RECENT_30_NO_CALL_DAY(254, "RECENT_30_NO_CALL_DAY"),// 近30天 无通话记录总天数


    ADVANCE_VERIFY_RULE(255, "ADVANCE_VERIFY_RULE"),// advance实名认证规则

    /* Tokopedia start*/
    RECENT_180_TOTAL_AMOUNT(300, "RECENT_180_TOTAL_AMOUNT"),// 近180天累计订单金额
    RECENT_30_TOTAL_AMOUNT(301, "RECENT_30_TOTAL_AMOUNT"),// 近30天累计订单金额
    RECENT_180_TOTAL_COUNT(302, "RECENT_180_TOTAL_COUNT"),// 近180天累计订单次数
    RECENT_30_TOTAL_COUNT(303, "RECENT_30_TOTAL_COUNT"),// 近30天累计订单次数

    AVG_ORDER_NUM(304, "AVG_ORDER_NUM"),// 月平均订单次数
    AVG_ORDER_AMOUNT(305, "AVG_ORDER_AMOUNT"),// 月平均订单金额

    MIN_AOUNT(306, "MIN_AOUNT"),// 单笔订单的最低价格
    MAX_AOUNT(307, "MAX_AOUNT"),// 单笔订单的最高价格

    AVG_AMOUNT(308, "AVG_AMOUNT"),// 单笔订单平均价格
    MID_AMOUNT(309, "MID_AMOUNT"),// 单笔订单价格的中位数
    MODE_AMOUNT(310, "MODE_AMOUNT"),// 单笔订单价格的众数

    END_DIFF_APPLY_DAY(311, "END_DIFF_APPLY_DAY"),// 尾笔订单距提交申请的天数
    FIRST_DIFFAPPLY_DAY(312, "FIRST_DIFFAPPLY_DAY"),// 首笔订单距提交申请的天数
    CROSS_DAY(313, "CROSS_DAY"),// 订单的累计跨越天数
    AVG_DAY(314, "AVG_DAY"),// 订单的平均间隔天数

    ADDRESS_SET(315, "ADDRESS_SET"),// 订单的地址个数

    TOKOPEDIA_BIRTHDAY(316, "TOKOPEDIA_BIRTHDAY"),// TOKOPEDIA生日不一致
    TOKOPEDIA_EMAIL(317, "TOKOPEDIA_EMAIL"),// TOKOPEDIA邮箱不一致
    TOKOPEDIA_MOBILE(318, "TOKOPEDIA_MOBILE"),// TOKOPEDIA手机号不一致

    SHOP_URL_SET(319, "SHOP_URL_SET"),// TOKOPEDIA购买的店铺个数
    IN_OUT_RATE(320, "IN_OUT_RATE"),// 支出占收入的比例


    DIFF_PHONE_NUM_COUNT(321, "DIFF_PHONE_NUM_COUNT"),// tokopedia去重手机号码个数(下单地址的手机号+注册手机号)
    MATCH_PHONE_COUNT(322, "MATCH_PHONE_COUNT"),// 用户手机号匹配到tokopedia收货地址中手机号的次数
    TO_ORDER_COUNT(323, "TO_ORDER_COUNT"),// 用户手机号在toko累计下单次数
    REGISTER_DIFF_DAYS(324, "REGISTER_DIFF_DAYS"),// tokopedia账号注册距提交订单的天数
    MATCH_NUM(325, "MATCH_NUM"),// tokopedia用户名匹配到uu用户姓名单词的个数

    BIG_DIRECT_COUNT(326, "BIG_DIRECT_COUNT"),// 大区出现的次数
    SMALL_DIRECT_COUNT(327, "SMALL_DIRECT_COUNT"),// 小区出现的次数
    DETAILED_COUNT(328, "DETAILED_COUNT"),// 详细地址的单词匹配到至少1个的次数
    ADDR_FLAG(329, "ADDR_FLAG"),// 大区、小区、详细地址未同时出现

    /* Tokopedia end*/

    /* Gojek start*/
    DISTANCE_180(350, "DISTANCE_180"),// 近180天累计乘车距离
    DISTANCE_30(351, "DISTANCE_30"),// 近30天累计乘车距离
    FARE_180(352, "FARE_180"),// 近180天累计乘车费用
    FARE_30(353, "FARE_30"),// 近30天累计乘车费用
    COUNT_180(354, "COUNT_180"),// 近180天累计乘车次数
    COUNT_30(355, "COUNT_30"),// 近30天累计乘车次数

    PICK_UP_180(356, "PICK_UP_180"),// 近180天累计上车地点个数
    PICK_UP_30(357, "PICK_UP_30"),// 近30天累计上车地点个数

    TAXI_TYPE_180(358, "TAXI_TYPE_180"),// 近180天累计乘车类型
    TAXI_TYPE_30(359, "TAXI_TYPE_30"),// 近30天累计乘车类型

    TAXI_TYPE_SPECIAL_180(360, "TAXI_TYPE_SPECIAL_180"),// 近180天累计乘坐GOLDEN/SILVER/BLUE BIRD的次数
    TAXI_TYPE_SPECIAL_30(361, "TAXI_TYPE_SPECIAL_30"),// 近30天累计乘坐GOLDEN/SILVER/BLUE BIRD的次数

    MIN_TIME_DIFF(362, "MIN_TIME_DIFF"),// 首笔订单乘车距提交申请的天数
    MAX_TIME_DIFF(363, "MAX_TIME_DIFF"),// 尾笔订单乘车距提交申请的天数

    MONTH_AVG_FARE(364, "MONTH_AVG_FARE"),// 月平均乘车费用
    MONTH_AVG_COUNT(365, "MONTH_AVG_COUNT"),// 月平均乘车次数

    AVG_FARE(366, "AVG_FARE"),// 平均乘车费用
    AVG_DISTANCE(367, "AVG_DISTANCE"),// 平均乘车距离
    FARE_MAX(368, "FARE_MAX"),// 单次乘车的最大费用
    DISTANCE_MAX(369, "DISTANCE_MAX"),// 单次乘车的最长距离
    PAYMENT_METHOD_SET(370, "PAYMENT_METHOD_SET"),// 支付类型次数
    CASH_SET(371, "CASH_SET"),// 现金支付次数
    MOBILENUMBER_DIFF(372, "MOBILENUMBER_DIFF"),// GOJEK手机号不一致
    EMAIL_DIFF(373, "EMAIL_DIFF"),// GOJEK邮箱是不一致

    HOME_ADDR_PICKUP_BOOLEAN(374, "HOME_ADDR_PICKUP_BOOLEAN"),// 乘车地（出发地）是否匹配现居地
    HOME_ADDR_DROPOFF_BOOLEAN(375, "HOME_ADDR_DROPOFF_BOOLEAN"),// 乘车地（目的地）是否匹配现居地
    SCHOOL_ADDR_PICKUP_BOOLEAN(376, "SCHOOL_ADDR_PICKUP_BOOLEAN"),// 乘车地（出发地）是否匹配学校地址（学生人群）
    SCHOOL_ADDR_DROPOFF_BOOLEAN(377, "SCHOOL_ADDR_DROPOFF_BOOLEAN"),// 乘车地（目的地）是否匹配学校地址（学生人群）
    COM_ADDR_PICKUP_BOOLEAN(378, "COM_ADDR_PICKUP_BOOLEAN"),// 乘车地（出发地）是否匹配公司地址（工作人群）
    COM_ADDR_DROPOFF_BOOLEAN(379, "COM_ADDR_DROPOFF_BOOLEAN"),// 乘车地（目的地）是否匹配公司地址（工作人群）

    MAX_HOME_ADDR_TIME(380, "MAX_HOME_ADDR_TIME"),// 最近一次包含居住地的打车订单距提交订单的天数
    MAX_SCHOOL_ADDR_TIME(381, "MAX_SCHOOL_ADDR_TIME"),// 最近一次包含居住地的打车订单距提交订单的天数
    MAX_COM_ADDR_TIME(382, "MAX_COM_ADDR_TIME"),// 最近一次包含居住地的打车订单距提交订单的天数

    MIN_HOME_ADDR_TIME(383, "MIN_HOME_ADDR_TIME"),// 首次包含居住地的打车订单距提交订单的天数
    MIN_SCHOOL_ADDR_TIME(384, "MIN_SCHOOL_ADDR_TIME"),// 首次包含学校地的打车订单距提交订单的天数
    MIN_COM_ADDR_TIME(385, "MIN_COM_ADDR_TIME"),// 首次包含公司地的打车订单距提交订单的天数
    MATCH_COMPANY_NUM(386, "MATCH_COMPANY_NUM"),// 首次包含公司地的打车订单距提交订单的天数
    /* Gojek end*/

    /* facebook start*/
    FACEBOOK_TOTAL_COMMENT_COUNT(1110001, "FACEBOOK_TOTAL_COMMENT_COUNT"),//历史累计评论数
    FACEBOOK_RECENT2MONTH_COMMENT_COUNT(1110002, "FACEBOOK_RECENT2MONTH_COMMENT_COUNT"),//近2个月累计评论数
    FACEBOOK_CURRENTMONTH_COMMENT_COUNT(1110003, "FACEBOOK_CURRENTMONTH_COMMENT_COUNT"),//当月评论数
    FACEBOOK_TOTAL_LIKES_COUNT(1110004, "FACEBOOK_TOTAL_LIKES_COUNT"),//历史累计点赞数
    FACEBOOK_RECENT2MONTH_LIKES_COUNT(1110005, "FACEBOOK_RECENT2MONTH_LIKES_COUNT"),//近2个月累点赞数
    FACEBOOK_CURRENTMONTH_LIKES_COUNT(1110006, "FACEBOOK_CURRENTMONTH_LIKES_COUNT"),//当月点赞数
    FACEBOOK_TOTAL_POST_COUNT(1110007, "FACEBOOK_TOTAL_POST_COUNT"),//历史累计帖子数
    FACEBOOK_RECENT2MONTH_POST_COUNT(1110008, "FACEBOOK_RECENT2MONTH_POST_COUNT"),//近2个月累计帖子数
    FACEBOOK_CURRENTMONTH_POST_COUNT(1110009, "FACEBOOK_CURRENTMONTH_POST_COUNT"),//当月帖子数
    FACEBOOK_MONTH_AVERAGE_COMMENT_COUNT(1110010, "FACEBOOK_MONTH_AVERAGE_COMMENT_COUNT"),//月平均点评数
    FACEBOOK_MONTH_AVERAGE_LIKES_COUNT(1110011, "FACEBOOK_MONTH_AVERAGE_LIKES_COUNT"),//月平均点赞数
    FACEBOOK_MONTH_AVERAGE_POST_COUNT(1110012, "FACEBOOK_MONTH_AVERAGE_POST_COUNT"),//月平均帖子数
    FACEBOOK_TOTAL_MONTHS_WITH_POST(1110013, "FACEBOOK_TOTAL_MONTHS_WITH_POST"),//累计发帖月份数
    FACEBOOK_TOTAL_MONTHS_WITHOUT_POST(1110014, "FACEBOOK_TOTAL_MONTHS_WITHOUT_POST"),//累计未发帖月份数
    FACEBOOK_ACADEMIC_NOT_CONTAIN(1110015, "FACEBOOK_ACADEMIC_NOT_CONTAIN"),//facebook学历和订单学历不一致
    FACEBOOK_DIFFDAYS_FOR_WORK_AND_APPLICATION(1110016,
        "FACEBOOK_DIFFDAYS_FOR_WORK_AND_APPLICATION"),//facebook最早工作时间和订单申请时间相差天数
    FACEBOOK_COMPANY_NOT_CONTAIN(1110017, "FACEBOOK_COMPANY_NOT_CONTAIN"),//facebook中公司和订单公司不一致
    /* facebook end*/

    /* 初借数据为空 start*/
    USER_CALL_RECORDS_KEY_INfO_EMPTY(600, "USER_CALL_RECORDS_KEY_INfO_EMPTY"),// 手机通话记录为空 4
    TOKOPEDIA_DATA_EMPTY(601, "TOKOPEDIA_DATA_EMPTY"),// Tokopedia的相关数据为空 8
    SHORT_MESSAGE_KEY_INfO_EMPTY(602, "SHORT_MESSAGE_KEY_INfO_EMPTY"),// 用户短信为空 5
    INSTALLED_APP_DATA_EMPTY(603, "INSTALLED_APP_DATA_EMPTY"),// 用户app列表为空 6
    IDENTITY_KEY_INfO_EMPTY(604, "IDENTITY_KEY_INfO_EMPTY"),// 用户身份证号为空 2
    GOJEK_DATA_EMPTY(605, "GOJEK_DATA_EMPTY"),// gojek的相关数据为空 9
    FACEBOOK_DATA_EMPTY(606, "FACEBOOK_DATA_EMPTY"),// facebook相关数据为空 10
    DEVICE_INFO_DATA_EMPTY(607, "DEVICE_INFO_DATA_EMPTY"),// 用户设备号为空 7
    FIRST_CONTACT_INFO_DATA_EMPTY(608, "FIRST_CONTACT_INFO_DATA_EMPTY"),// 用户第一联系人为空 3
    SECOND_CONTACT_INFO_DATA_EMPTY(609, "SECOND_CONTACT_INFO_DATA_EMPTY"),// 用户第二联系人为空 3
    CONTACT_KEY_INfO_EMPTY(610, "CONTACT_KEY_INfO_EMPTY"),// 手机通讯录为空 3
    /* 初借数据为空 end*/


    /* 复借数据为空 start*/
    MULTI_CAll_DATA_EMPTY(500, "MULTI_CAll_DATA_EMPTY"),// 1027
    MULTI_CONTACT_DATA_EMPTY(501, "MULTI_CONTACT_DATA_EMPTY"),// 1003
    MULTI_INSTALLED_APP_DATA_EMPTY(502, "MULTI_INSTALLED_APP_DATA_EMPTY"),// 1083
    MULTI_SHORT_MESSAGE_DATA_EMPTY(503, "MULTI_SHORT_MESSAGE_DATA_EMPTY"),// 1043
    MULTI_LAST_LOAN_EMPTY_DATA_EMPTY(504, "MULTI_LAST_LOAN_EMPTY_DATA_EMPTY"),// 997
    /* 复借数据为空 end*/


    /*复借 start*/
    MULTI_LAST_TIME_DAY(400, "MULTI_LAST_TIME_DAY"),// 上一次贷款逾期超过15天

    MULTI_QC_CONTACT_COUNT(401, "MULTI_QC_CONTACT_COUNT"),// 去重通讯录手机号码条数
    MULTI_CONTACT_SENSITIVI_COUNT(402, "MULTI_CONTACT_SENSITIVI_COUNT"),// 通讯录命中敏感词个数
    MULTI_CONTACT_SAMEJOB_COUNT(403, "MULTI_CONTACT_SAMEJOB_COUNT"),// 通讯录同业词个数
//    MULTI_TELEPHONE_30_COUNT(404, "MULTI_TELEPHONE_30_COUNT"),// 借款人手机号命中逾期30天以上黑名单用户次数
//    MULTI_CONTACT_30_COUNT(405, "MULTI_CONTACT_30_COUNT"),// 借款人通讯录命中逾期30天以上黑名单用户次数
//
//    MULTI_TELEPHONE_30_BLACKLIST_COUNT(406, "MULTI_TELEPHONE_30_BLACKLIST_COUNT"),// 通话记录号码命中逾期30天以上黑名单次数
    MULTI_CONTACT_LAST_TIME(407, "MULTI_CONTACT_LAST_TIME"),// 最后一次通话距提交订单的天数（单位：天）
    MULTI_NIGHT_RATE(408, "MULTI_NIGHT_RATE"),// 近15天内夜间活跃占比

    MULTI_SMS_OVERDUE_COUNT(409, "MULTI_SMS_OVERDUE_COUNT"),// 短信逾期词个数
    MULTI_SMS_NEGATIVE_COUNT(410, "MULTI_SMS_NEGATIVE_COUNT"),// 短信负面词个数
    MULTI_SMS_SAME_COUNT(411, "MULTI_SMS_SAME_COUNT"),// 短信同业词个数
    MULTI_SMS15BLACKLISTCOUNT(412, "MULTI_SMS15BLACKLISTCOUNT"),// 短信通话对象命中逾期15天以上黑名单
    MULTI_SMS_REFUSE_COUNT(413, "MULTI_SMS_REFUSE_COUNT"),// 近30天内被拒绝的短信条数
    MULTI_ALL_SMS_COUNT(414, "MULTI_ALL_SMS_COUNT"),// 近30天内出现逾期的"累计"短信条数
    MULTI_QC_SMS_COUNT(415, "MULTI_QC_SMS_COUNT"),// 近30天内出现逾期的"去重"短信条数
    MULTI_SMS15SET_COUNT(416, "MULTI_SMS15SET_COUNT"),// 近15天手机号码的短信条数
    MULTI_SMS_OVERDUE_MORETHAN_15DAYS_COUNT(417, "MULTI_SMS_OVERDUE_MORETHAN_15DAYS_COUNT"), // 命中逾期大于15天的短信条数
    MULTI_SMS_OVERDUE_LESSTHAN_15DAYS_COUNT(418, "MULTI_SMS_OVERDUE_LESSTHAN_15DAYS_COUNT"), // 短信出现逾期10-15（含）天的平台个数
    MULTI_SMS_OVERDUE_MAX_DAYS(419, "MULTI_SMS_OVERDUE_MAX_DAYS"), // 短信中出现的最大逾期天数

    MULTI_USER_INSTALLED_SENSITIVE_APP_COUNT(417, "MULTI_USER_INSTALLED_SENSITIVE_APP_COUNT"),// 本次贷款app个数
    MULTI_USER_INSTALLED_SENSITIVE_APP_RATE(418, "MULTI_USER_INSTALLED_SENSITIVE_APP_RATE"),// 本次贷款app占比
    MULTI_ADD_USER_INSTALLED_SENSITIVE_APP_COUNT(419, "MULTI_ADD_USER_INSTALLED_SENSITIVE_APP_COUNT"),// 贷款APP的增加个数
    MULTI_ADD_USER_INSTALLED_SENSITIVE_APP_RATE(420, "MULTI_ADD_USER_INSTALLED_SENSITIVE_APP_RATE"),// 贷款APP占比变化
    /*复借 end*/



    COMB_SEX_MGS_NEGATIVE_COUNT_MSG_COUNT(11200001,"COMB_SEX_MGS_NEGATIVE_COUNT_MSG_COUNT"),
    COMB_MGS_OVERDUE_COUNT_RECENT30CALLIN_MISSEDRATE(11200002,"COMB_MGS_OVERDUE_COUNT_RECENT30CALLIN_MISSEDRATE"),
    COMB_SEX_EVENING_CALL_RATE_AGE(11200003,"COMB_SEX_EVENING_CALL_RATE_AGE"),
    COMB_SEX_RECENT30_MISSEDCALLRATE(11200004,"COMB_SEX_RECENT30_MISSEDCALLRATE"),
    COMB_SEX_RECENT30_MISSEDCALLINDATE(11200005,"COMB_SEX_RECENT30_MISSEDCALLINDATE"),
    COMB_RECENT30_MISSEDCALLRATE_CALLTIME(11200006,"COMB_RECENT30_MISSEDCALLRATE_CALLTIME"),
    COMB_SEX_YITUSCORE(11200007,"COMB_SEX_YITUSCORE"),
    COMB_SEX_AGE_MISSEDCALLINRATE(11200008,"COMB_SEX_AGE_MISSEDCALLINRATE"),
    COMB_DRIVERLICENSE_YITUSCORE(11200009,"COMB_DRIVERLICENSE_YITUSCORE"),

    // 新上规则
    COMB_2_FEMALE_FREE_PHONE_CHECK(11200100,"COMB_2_FEMALE_FREE_PHONE_CHECK"),// 女性免电核规则，初审，复审要用

    COMB_2_RECORD_90SMSCOUNT_SEX(11200101,"COMB_2_RECORD_90SMSCOUNT_SEX"),// 无通话记录&90天逾期短信条数&性别
    COMB_2_RECORD_30SMSCOUNT(11200102,"COMB_2_RECORD_30SMSCOUNT"),// 无通话记录&30天被拒绝短信条数
    COMB_2_COMPADDRESS_HOMEADDRESS(11200103,"COMB_2_COMPADDRESS_HOMEADDRESS"),// 公司地址&居住地址
    COMB_2_SEX_APPRATE_PHONEUSED(11200104,"COMB_2_SEX_APPRATE_PHONEUSED"),// 性别&用户安装敏感APP占比&手机使用时长

    // 新上规则 2018-03-19
    COMB_3_SEX_PHONE_LANGUAGE(11200105,"COMB_3_SEX_PHONE_LANGUAGE"),// 女性&手机语言
    COMB_3_NETTYPE_PICTURENUMBER(11200106,"COMB_3_NETTYPE_PICTURENUMBER"),// 网络种类&手机图片
    COMB_3_TOTALMEMORY_PICTURENUMBER(11200107,"COMB_3_TOTALMEMORY_PICTURENUMBER"),// 手机总内存&手机图片
    COMB_3_CHILDRENAMOUNT(11200108,"COMB_3_CHILDRENAMOUNT"),// 孩子数量


    // 2018-03-28 新规则
    COMB_RECENT30_MISCALL_FEMALE_MARRIAGE_EDUCATION(11200109,"COMB_RECENT30_MISCALL_FEMALE_MARRIAGE_EDUCATION"),//近30天打入未接通占比=0&女性&已婚&本科
    COMB_AGE_FEMALE_EDUCATION(11200110,"COMB_AGE_FEMALE_EDUCATION"),//年龄>=34&女性&本科
    COMB_MALE_MARRIAGE_EDUCATION(11200111,"COMB_MALE_MARRIAGE_EDUCATION"),//男性&单身&高中及以下
    COMB_MOBILEUSAGETIME_MALE_MARRIAGE(11200112,"COMB_MOBILEUSAGETIME_MALE_MARRIAGE"),//手机使用时长[0,16)&男性&单身
    COMB_CALLANDCONTACT_MALE_MARRIAGE_EDUCATION(11200113,"COMB_CALLANDCONTACT_MALE_MARRIAGE_EDUCATION"),//近30天的通话记录中，出现在通讯录中的有效去重通话号码个数>=36&男性&单身&高中及以下


    //复借组合规则
    COMB_REBORROW_MEMORY_EDUCATION_SEX(11300001,"COMB_REBORROW_MEMORY_EDUCATION_SEX"),//手机内存&学历& 性别
    COMB_REBORROW_OVERDUEDAYS_EVENING_RATIO(11300002,"COMB_REBORROW_OVERDUEDAYS_EVENING_RATIO"),//上一次贷款逾期天数-复借>3&近15天内夜间活跃占比-复借>=0.05

    COMB_REBORROW_FIRSTOVERDUEDAYS(11300003,"COMB_REBORROW_FIRSTOVERDUEDAYS"),//首借贷款逾期天数



    MULTI_SMS_RECENT30_COUNT(11400001,"MULTI_SMS_RECENT30_COUNT"),//短信30天条数
    MULTI_CALLIN_NOTRECEIVED_RATIO_RECENT30(11400002,"MULTI_CALLIN_NOTRECEIVED_RATIO_RECENT30"),//近30天打入未接通占比
    MULTI_CALLIN_NOTRECEIVED_COUNT_RECENT30(11400003,"MULTI_CALLIN_NOTRECEIVED_COUNT_RECENT30"),//近30天打入未接通次数

    MULTI_NOTCONNECTED_COUNT_RECENT30(11400004,"MULTI_NOTCONNECTED_COUNT_RECENT30"),//近30天内未接通电话次数
    MULTI_NOTCONNECTED_RATIO_RECENT30(11400005,"MULTI_NOTCONNECTED_RATIO_RECENT30"),//近30天内未接通电话占比
    MULTI_TOTAL_DURATION_RECENT30(11400006,"MULTI_TOTAL_DURATION_RECENT30"),//近30天通话时长
    MULTI_TOTAL_TIMES_RECENT30(11400007,"MULTI_TOTAL_TIMES_RECENT30"),//近30天通话次数
    MULTI_CALLIN_DURATION_RECENT30(11400008,"MULTI_CALLIN_DURATION_RECENT30"),//近30天打入通话时长
    MULTI_CALLOUT_PHONES_RECENT30(11400009,"MULTI_CALLOUT_PHONES_RECENT30"),//近30天主叫号码数
    MULTI_CALLIN_PHONES_RECENT30(11400010,"MULTI_CALLIN_PHONES_RECENT30"),//近30天被叫号码数
    MULTI_NOCONNECT_DAYS_RECENT180(11400011,"MULTI_NOCONNECT_DAYS_RECENT180"),//180天内的无通话天数
    MULTI_CONNECT_FIRSTCONTACT_TIMES_RECENT30(11400012,"MULTI_CONNECT_FIRSTCONTACT_TIMES_RECENT30"),//近30天与第一联系人通话次数
    MULTI_CONNECT_SECONDCONTACT_TIMES_RECENT30(11400013,"MULTI_CONNECT_SECONDCONTACT_TIMES_RECENT30"),//近30天与第二联系人通话次数
    MULTI_SAME_IP_APPLYTIMES(11400014,"MULTI_SAME_IP_APPLYTIMES"),//同一天内同一个IP的申请次数
    MULTI_GOJEK_SAMEPHONE(11400015,"MULTI_GOJEK_SAMEPHONE"),//gojek手机号是否一致
    MULTI_GOJEK_MAXFEE(11400016,"MULTI_GOJEK_MAXFEE"),//单次乘车的最大费用
    MULTI_FACEBOOK_MONTH_AVERAGE_REMARDS(11400017,"MULTI_FACEBOOK_MONTH_AVERAGE_REMARDS"),//facebook月均评论数
    MULTI_TOTAL_APPS(11400018,"MULTI_TOTAL_APPS"),//累计app个数
    MULTI_SAME_DEVICE_HITCOUNT(11400019,"MULTI_SAME_DEVICE_HITCOUNT"),//同一设备号命中2人及以

    COMB_FIRST_CONTACT_RECENT90CALL_FEMALE(11500001,
        "COMB_FIRST_CONTACT_RECENT90CALL_FEMALE"),//第一联系人,近90天,通话时长&女
    COMB_RECENT180RIDETIMES_FEMALE(11500002, "COMB_RECENT180RIDETIMES_FEMALE"),//近180天累计乘车次数&女

    COMB_DIFFDAYSOFEARLIESTMSG_RECENT90OVEDUESMSG_FEMALE(11500003,
        "COMB_DIFFDAYSOFEARLIESTMSG_RECENT90OVEDUESMSG_FEMALE"),//女性&最早一条短信时间&近90天逾期短信条数（按号码去重）

    COMB_SAMEIPCOUNT_150RMB(11500004,
        "COMB_SAMEIPCOUNT_150RMB"),//同一天内同一个IP的申请次数&男

    COMB_RECENT180RIDETIMES_MAXRIDEFEE_MALE(11500005,
        "COMB_RECENT180RIDETIMES_MAXRIDEFEE_MALE"),//近180天累计乘车次数&单次乘车的最大费用&男

    COMB_RECENT90FIRSTCONTACTCALL_FACEBOOKNOPOSTMONTHS_MALE(11500006,
        "COMB_RECENT90FIRSTCONTACTCALL_FACEBOOKNOPOSTMONTHS_MALE"),//第一联系人,近90天,通话时长&facebook未发帖的月份个数&男

    COMB_FIRST_CONTACT_AND_SECOND_CONTACT_NOT_IN_CONTACTS(11500007,
        "COMB_FIRST_CONTACT_AND_SECOND_CONTACT_NOT_IN_CONTACTS"),//2个紧急联系人均不在通讯录

    COMB_RECENT30CALLIN_MOBILEUSEDTIMES_FEMALE(11500008,
        "COMB_RECENT30CALLIN_MOBILEUSEDTIMES_FEMALE"),//女性&近30天打入通话时长&手机使用时长

    COMB_DIFFDAYSOFEARLIESTMSG_MALE(11500009,
        "COMB_DIFFDAYSOFEARLIESTMSG_MALE"),//男性&最早一条短信时间距申请时间的天数

    COMB_MOBILEUSEDTIMES_RECENT30NOCONNECTRATIO_MALE(11500010,
        "COMB_MOBILEUSEDTIMES_RECENT30NOCONNECTRATIO_MALE"),//男性&手机使用时长&近30天打入未接通占比

    //20180621
    COMB_MOBILE_LANG_AND_CAP(11600001, "COMB_MOBILE_LANG_AND_CAP"),//手机语言&手机总容量

    COMB_MOBILE_CAP_FEMALE_EDUCATION(11600002, "COMB_MOBILE_CAP_FEMALE_EDUCATION"),//手机总容量&女&学历

    COMB_MOBILE_CAP_MALE_MARITAL_EDUCATION_DIFFDAYSOFLASTCALL_RECENT30CALLIN(11600003,
        "COMB_MOBILE_CAP_MALE_MARITAL_EDUCATION_DIFFDAYSOFLASTCALL_RECENT30CALLIN"),//男性&婚姻&学历&最后通话&30天打入时长&手机容量

    COMB_NOCALLOFFIRSTSECONDLINKMAN_MALE_MARITAL(11600004,
        "COMB_NOCALLOFFIRSTSECONDLINKMAN_MALE_MARITAL"),//第一，第二联系人均无通话记录&男&单身

    COMB_MOBILE_CAP_FIRSTLINKEMANRECENT180CALLCOUNT_MALE(11600005,
        "COMB_MOBILE_CAP_FIRSTLINKEMANRECENT180CALLCOUNT_MALE"),//第一联系人,近180天,通话次数&手机总内存&男

    COMB_MOBILE_CAP_MARITAL_EDUCATION(11600006, "COMB_MOBILE_CAP_MARITAL_EDUCATION"),//婚姻&手机总容量&学历

    //20180626
    //近30天呼入占比&最早一条短信时间距申请时间的天数&近90天无通话记录总天数&女
    COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE(11700001, "COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE"),

    //近90天打入通话次数&最早一条短信时间距申请时间的天数&学历&女
    COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE(11700002, "COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE"),

    //手机使用时长（单位：天）&最早一条短信时间距申请时间的天数&孩子数量&女
    COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE(11700003, "COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE"),

    //近90天打入通话次数&近90天无通话记录总天数&学历&男
    COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE(11700004, "COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE"),


    CASH2_FACE_PLUS_PLUS_SCORE(11800001,"CASH2_FACE_PLUS_PLUS_SCORE"),

    INSTALL_APP_COUNT(11900001,"INSTALL_APP_COUNT"),//首借累计app个数
//    MOBILE_IS_EMERGENCYTEL_FOR_OVERDUE30USERS(11900002,"MOBILE_IS_EMERGENCYTEL_FOR_OVERDUE30USERS"),//借款人手机号码是逾期30天以上用户的紧急联系人
    MOBILE_AS_EMERGENCYTEL_COUNT(11900003,"MOBILE_AS_EMERGENCYTEL_COUNT"),//借款人手机号码已作为紧急联系人出现次数
//    EMERGENCYTEL_IS_OVERDUE30USERS(11900004,"EMERGENCYTEL_IS_OVERDUE30USERS"),//紧急联系人手机号码是逾期30天以上用户
    EMERGENCYTEL_NOT_IN_CALLRECORD(11900005,"EMERGENCYTEL_NOT_IN_CALLRECORD"),//两个紧急联系人均不在通话记录中
    DEVICEID_IS_OVERDUE30USERS(11900006,"DEVICEID_IS_OVERDUE30USERS"),//设备号命中逾期30天以上用户的设备号
//    CONTACT_HIT_OVERDUE30USERS_COUNT(11900007,"CONTACT_HIT_OVERDUE30USERS_COUNT"),//通讯录命中逾期30天黑名单次数
//    CALL_RECORD_HIT_OVERDUE30USERS_COUNT(11900008,"CALL_RECORD_HIT_OVERDUE30USERS_COUNT"),//通话记录对象命中逾期30天及以上黑名单


    FACEBOOK_COMPANY_CONTAIN(1200001, "FACEBOOK_COMPANY_CONTAIN"),//facebook中公司和订单公司一致

    USER_DEVICE_IMEI(1210001,"USER_DEVICE_IMEI"),//同一个imei命中不同的人两次及以上

    IMEI_IN_BLACK_LIST(1220001,"IMEI_IN_BLACK_LIST"),//imei在yqg黑名单中

    //20180731
//    IMEI_IN_OVERDUE30_BLACK_LIST_USER(1230001,"IMEI_IN_OVERDUE30_BLACK_LIST_USER"),//申请手机IMEI命中逾期30天以上用户IMEI黑名单
//    ID_CARD_IN_OVERDUE30_BLACK_LIST_USER(1230002,"ID_CARD_IN_OVERDUE30_BLACK_LIST_USER"),//申请人身份证命中逾期30天以上用户身份证号黑名单
//    MOBILE_IN_OVERDUE30_BLACK_LIST(1230011,"MOBILE_IN_OVERDUE30_BLACK_LIST"),//申请手机号命中逾期30天以上用户手机号黑名单
//    //申请人的紧急联系人手机号码是逾期30天以上用户的紧急联系人
//    EMERGENCY_TEL_IS_OVERDUE30_BLACK_LIST_USER_EMERGENCY_TEL(1230003,"EMERGENCY_TEL_IS_OVERDUE30_BLACK_LIST_USER_EMERGENCY_TEL"),
//    //申请人银行卡命中逾期30天以上用户银行卡号黑名单
//    BANKCARD_NUMBER_IN_OVERDUE30_BLACK_LIST_USER_BANKCARD(1230004,"BANKCARD_NUMBER_IN_OVERDUE30_BLACK_LIST_USER_BANKCARD"),
//    //申请人的紧急联系人手机号码命中逾期15天以上用户的次数
//    EMERGENCY_TEL_IN_OVERDUE15_BLACK_LIST_USER_COUNT(1230005,"EMERGENCY_TEL_IN_OVERDUE15_BLACK_LIST_USER_COUNT"),
    //申请人手机号码是逾期15天以上用户的紧急联系人
    MOBILE_IN_OVERDUE15_BLACK_LIST_USER_EMERGENCY_TEL(1230006,"MOBILE_IN_OVERDUE15_BLACK_LIST_USER_EMERGENCY_TEL"),
    //申请人短信通话对象命中逾期15天以上黑名单CONTACT_PHONES_IN_OVERDUE15_BLACK_LIST_USER_COUNT
    SMS_PHONES_IN_OVERDUE15_BLACK_LIST_USER(1230007,"SMS_PHONES_IN_OVERDUE15_BLACK_LIST_USER"),
    //申请人通讯录号码命中逾期15天黑名单个数
    CONTACT_PHONES_IN_OVERDUE15_BLACK_LIST_USER_COUNT(1230008,"CONTACT_PHONES_IN_OVERDUE15_BLACK_LIST_USER_COUNT"),
    MOBILE_IS_FRAUD_USER_EMERGENCY_TEL(1230009,"MOBILE_IS_FRAUD_USER_EMERGENCY_TEL"),//申请人手机号命中欺诈用户的紧急联系人
    MOBILE_IS_FRAUD_USER_CALL_RECORD_COUNT(1230010,"MOBILE_IS_FRAUD_USER_CALL_RECORD_COUNT"),//申请人手机号命中欺诈用户的通话记录次数


    //20180806
    HAS_INSURANCE_CARD(1240001,"HAS_INSURANCE_CARD"),//有无保险卡
    COMB_TAX_NUMBER_RECENT30INRATION_APPCOUNT_MALE(1240002,"COMB_TAX_NUMBER_RECENT30INRATION_APPCOUNT_MALE"),//有税卡&近30天呼入占比&首借累计app个数&男
    COMB_TAX_NUMBER_RECENT30INRATION_APPCOUNT_FEMALE(1240003,"COMB_TAX_NUMBER_RECENT30INRATION_APPCOUNT_FEMALE"),//有税卡&近30天呼入占比&首借累计app个数&女

    MULTI_IMEI_IS_FRAUD_USER(1240004,"MULTI_IMEI_IS_FRAUD_USER"),//申请人imei命中欺诈用户黑名单-复借

    PROVINCE_IN_EARTHQUAKE_AREA(1250001,"PROVINCE_IN_EARTHQUAKE_AREA"),//省份在震区


    NON_REVIEW_POSITION_NAMES(1260001,"NON_REVIEW_POSITION_NAMES"),//职业是医务人员或老师或公务员
    NON_REVIEW_RELIGION(1260002,"NON_REVIEW_RELIGION"),//宗教是天主教或印度教
    MOBILE_JAILBREAK(1260003,"MOBILE_JAILBREAK"),//已越狱
    MALE_SALARY_MEMORY(1260004,"MALE_SALARY_MEMORY"),//男&月收入&手机内存
    CALL_RECORD_RECENT30_DISTINCT_NUMBERS(1260005,"CALL_RECORD_RECENT30_DISTINCT_NUMBERS"), //近30天通话号码去重个数
    CALL_RECORD_RECENT90_DISTINCT_NUMBERS(1260006,"CALL_RECORD_RECENT90_DISTINCT_NUMBERS"), //近90天通话号码去重个数
    CALL_RECORD_RECENT30_CALL_IN_DISTINCT_NUMBERS(1260007,"CALL_RECORD_RECENT30_CALL_IN_DISTINCT_NUMBERS"), //近30天被叫号码去重个数
    CALL_RECORD_RECENT90_CALL_IN_DISTINCT_NUMBERS(1260008,"CALL_RECORD_RECENT90_CALL_IN_DISTINCT_NUMBERS"), //近90天被叫号码去重个数
    CALL_RECORD_RECENT90_STRANGE_NOT_CONNECT_RATIO(1260009,"CALL_RECORD_RECENT90_STRANGE_NOT_CONNECT_RATIO"), //近90天通话记录中陌生号码打入未接通占比
    SMS_OVERDUE15_COUNT_MALE(1260010,"SMS_OVERDUE15_COUNT_MALE"), //命中逾期大于15天的短信条数&男
    SMS_OVERDUE15_COUNT_FEMALE(1260011,"SMS_OVERDUE15_COUNT_FEMALE"), //命中逾期大于15天的短信条数&女

    MOBILE_IN_FRAUD_USER(1270001,"MOBILE_IN_FRAUD_USER"),//手机号在欺诈用户列表
    ID_CARD_NO_IN_FRAUD_USER(1270002,"ID_CARD_NO_IN_FRAUD_USER"),//身份证号在欺诈用户列表

    //20180825
    PHONE_BRAND(1280001,"PHONE_BRAND"),//手机品牌为ADVAN或Smartfren

    //20180827
    HIT_FRAUD_USER_INFO(1290001,"HIT_FRAUD_USER_INFO"),//命中欺诈用户组合属性
    MULTI_HIT_FRAUD_USER_INFO(1290002,"MULTI_HIT_FRAUD_USER_INFO"),//命中欺诈用户组合属性-复借

    //20180831
    RECENT30_EVENING_CALL_RATE_MALE(1300001,"RECENT30_EVENING_CALL_RATE_MALE"),//近30天内夜间活跃占比&男
    RECENT30_CALL_IN_MISSED_RATE_RECENT30_CALL_COUNT(1300002,"RECENT30_CALL_IN_MISSED_RATE_RECENT30_CALL_COUNT"),//近30天打入未接通占比&近30天通话次数
    NO_TAX_NUMBER_APP_COUNT_MALE(1300003,"NO_TAX_NUMBER_APP_COUNT_MALE"),//无税号&首借累计app个数&男
    NO_TAX_NUMBER_APP_COUNT_FEMALE(1300004,"NO_TAX_NUMBER_APP_COUNT_FEMALE"),//无税号&首借累计app个数&女
    DISTINCT_CONTACT_COUNT_RECENT90_CALLIN_DISTINCT_NUMBERS(1300005,"DISTINCT_CONTACT_COUNT_RECENT90_CALLIN_DISTINCT_NUMBERS"),//去重通讯录个数&近90天被叫号码去重个数

    //20180904
    AUTO_CALL_REJECT_OWNER_CALL_INVALID(1310001,"AUTO_CALL_REJECT_OWNER_CALL_INVALID"),//外呼本人号码拒绝
    AUTO_CALL_REJECT_OWNER_EXCEED_LIMIT(1310002,"AUTO_CALL_REJECT_OWNER_EXCEED_LIMIT"),//外呼本人号码超过次数任然未接通
    AUTO_CALL_REJECT_LINKMAN_VALID_COUNT(1310003,"AUTO_CALL_REJECT_LINKMAN_VALID_COUNT"),//紧急联系人外呼有效个数小于2
    AUTO_CALL_REJECT_BACKUP_LINKMAN_VALID_COUNT(1310004,"AUTO_CALL_REJECT_BACKUP_LINKMAN_VALID_COUNT"),//备选联系人外呼有效个数小于6
    AUTO_CALL_REJECT_BACKUP_LINKMAN_VALID_COUNT_100RMB_PRODUCT(1310004,"AUTO_CALL_REJECT_BACKUP_LINKMAN_VALID_COUNT_100RMB_PRODUCT"),
    //备选联系人外呼有效个数小于3--100rmb产品

    MULTI_AUTO_CALL_REJECT_LINKMAN_VALID_COUNT(1310005,"MULTI_AUTO_CALL_REJECT_LINKMAN_VALID_COUNT"),//紧急联系人外呼有效个数小于2
    MULTI_AUTO_CALL_REJECT_BACKUP_LINKMAN_VALID_COUNT(1310006,"MULTI_AUTO_CALL_REJECT_BACKUP_LINKMAN_VALID_COUNT"),//备选联系人外呼有效个数小于6

    //20180913
    DISTINCT_CONTACT_PHONE_MALE(1320001,"DISTINCT_CONTACT_PHONE_MALE"),//去重通讯录个数&男
    DISTINCT_CONTACT_PHONE_FEMALE(1320002,"DISTINCT_CONTACT_PHONE_FEMALE"),//去重通讯录个数&女
    RECENT90_DISTINCT_CALL_IN_NUMBERS_MALE(1320003,"RECENT90_DISTINCT_CALL_IN_NUMBERS_MALE"),//近90天去重被叫号码个数&男


    //20180918
    IMEI_IN_OVERDUE15_BLACKLIST(1330001,"IMEI_IN_OVERDUE15_BLACKLIST"),//申请手机IMEI命中逾期15天以上用户IMEI黑名单
    ID_CARD_IN_OVERDUE15_BLACKLIST(1330002,"ID_CARD_IN_OVERDUE15_BLACKLIST"),//申请人身份证命中逾期15天以上用户身份证号黑名单
    MOBILE_IN_OVERDUE15_BLACKLIST(1330003,"MOBILE_IN_OVERDUE15_BLACKLIST"),//申请手机号命中逾期15天以上用户手机号黑名单
    BANKCARD_IN_OVERDUE15_BLACKLIST(1330004,"BANKCARD_IN_OVERDUE15_BLACKLIST"),//申请人银行卡命中逾期15天以上用户银行卡号黑名单
    EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_OVERDUE15_BLACKLIST(1330005,"EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_OVERDUE15_BLACKLIST"),//申请人的紧急联系人手机号码是逾期15天以上用户的紧急联系人

    EMERGENCY_TEL_IN_OVERDUE15_BLACKLIST(1330006,"EMERGENCY_TEL_IN_OVERDUE15_BLACKLIST"),//紧急联系人手机号码是逾期15天以上用户
    MOBILE_IN_CONTACT_OF_OVERDUE15_BLACKLIST(1330007,"MOBILE_IN_CONTACT_OF_OVERDUE15_BLACKLIST"),//申请手机号命中逾期15天用户的通讯录
    MOBILE_IN_CALL_RECORD_OF_OVERDUE15_BLACKLIST(1330008,"MOBILE_IN_CALL_RECORD_OF_OVERDUE15_BLACKLIST"),//申请手机号命中逾期15天用户的通话记录
    MOBILE_IN_SHORT_MSG_OF_OVERDUE15_BLACKLIST(1330009,"MOBILE_IN_SHORT_MSG_OF_OVERDUE15_BLACKLIST"),//申请手机号命中逾期15天用户的短信对象
    CONTACT_PHONE_IN_OVERDUE15_BLACKLIST(1330010,"CONTACT_PHONE_IN_OVERDUE15_BLACKLIST"),//通讯录命中逾期15天黑名单
    CALL_RECORD_PHONE_IN_OVERDUE15_BLACKLIST(1330011,"CALL_RECORD_PHONE_IN_OVERDUE15_BLACKLIST"),//通话记录对象命中逾期15天及以上黑名单

    //复借--黑名单
    MULTI_MOBILE_IN_OVERDUE15_BLACK_LIST(1330012,"MULTI_MOBILE_IN_OVERDUE15_BLACK_LIST"),//借款人手机号命中逾期15天以上黑名单用户
    MULTI_CONTACT_PHONE_IN_OVERDUE15_COUNT(1330013,"MULTI_CONTACT_PHONE_IN_OVERDUE15_COUNT"),//通讯录对象命中逾期15天以上黑名单用户次数
    MULTI_CALL_RECORD_PHONE_IN_OVERDUE15_COUNT(1330014,"MULTI_CALL_RECORD_PHONE_IN_OVERDUE15_COUNT"),//通话记录号码命中逾期15天以上黑名单次数

    FIRST_LINKMAN_EXISTS(1330015,"FIRST_LINKMAN_EXISTS"),//第一紧急联系人相同
    EMAIL_EXISTS(1330016,"EMAIL_EXISTS"),//邮箱相同

    FIRST_LINKMAN_EXISTS_NOT_OVERDUE(1330015,"FIRST_LINKMAN_EXISTS_NOT_OVERDUE"),//第一紧急联系人相同
    EMAIL_EXISTS_NOT_OVERDUE(1330016,"EMAIL_EXISTS_NOT_OVERDUE"),//邮箱相同

    FIRST_LINKMAN_EXISTS_OVERDUE(1330015,"FIRST_LINKMAN_EXISTS_OVERDUE"),//第一紧急联系人相同
    EMAIL_EXISTS_OVERDUE(1330016,"EMAIL_EXISTS_OVERDUE"),//邮箱相同


    SAME_WORK_ADDRESS_AND_ORDER_ADDRESS_EXISTS(1330017,"SAME_WORK_ADDRESS_AND_ORDER_ADDRESS_EXISTS"),//工作地址&下单位置(smallDirect和detailed相同)
    SAME_HOME_ADDRESS_AND_ORDER_ADDRESS_EXISTS(1330018,"SAME_HOME_ADDRESS_AND_ORDER_ADDRESS_EXISTS"),//工作地址&下单位置
    SAME_WORK_ADDRESS_AND_HOME_ADDRESS_EXISTS(1330019,"SAME_WORK_ADDRESS_AND_HOME_ADDRESS_EXISTS"),//工作地址&下单位置


    //逾期7天
    CALL_RECORD_PHONE_IN_OVERDUE7_BLACKLIST(1330020,"CALL_RECORD_PHONE_IN_OVERDUE7_BLACKLIST"),//通话记录对象命中逾期7天及以上黑名单
    IMEI_IN_OVERDUE7_BLACKLIST(1330022,"IMEI_IN_OVERDUE7_BLACKLIST"),//申请手机IMEI命中逾期7天以上用户IMEI黑名单
    ID_CARD_IN_OVERDUE7_BLACKLIST(1330023,"ID_CARD_IN_OVERDUE7_BLACKLIST"),//申请人身份证命中逾期7天以上用户身份证号黑名单
    MOBILE_IN_OVERDUE7_BLACKLIST(1330024,"MOBILE_IN_OVERDUE7_BLACKLIST"),//申请手机号命中逾期7天以上用户手机号黑名单
    BANKCARD_IN_OVERDUE7_BLACKLIST(1330025,"BANKCARD_IN_OVERDUE7_BLACKLIST"),//申请人银行卡命中逾期7天以上用户银行卡号黑名单
    EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_OVERDUE7_BLACKLIST(13300216,"EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_OVERDUE7_BLACKLIST"),//申请人的紧急联系人手机号码是逾期7天以上用户的紧急联系人
    MOBILE_IS_EMERGENCY_TEL_FOR_OVERDUE7_BLACK(1330027,"MOBILE_IS_EMERGENCY_TEL_FOR_OVERDUE7_BLACK"),//申请人手机号码是逾期7天以上用户的紧急联系人
    EMERGENCY_TEL_IN_OVERDUE7_BLACKLIST(1330028,"EMERGENCY_TEL_IN_OVERDUE7_BLACKLIST"),//申请人的紧急联系人手机号码是逾期7天以上用户

    IS_IOS(1330029,"IS_IOS"),//是否ios设备
    HAS_FAMILY_CARD(1330030,"HAS_FAMILY_CARD"),//是否ios设备

    CITY_IN_EARTHQUAKE_AREA(1340001,"CITY_IN_EARTHQUAKE_AREA"),//居住城市属于震区

    //敏感用户
    HIT_SENSITIVE_USER_INFO(1340003,"HIT_SENSITIVE_USER_INFO"),//命中敏感人员身份证号或手机号
    MULTI_HIT_SENSITIVE_USER_INFO(1340004,"MULTI_HIT_SENSITIVE_USER_INFO"),//命中敏感人员身份证号或手机号
    //历史订单
    MULTI_APPLY_COUNT(1350001,"MULTI_APPLY_COUNT"),//申请次数
    MULTI_SUCCESS_RATIO(1350002,"MULTI_SUCCESS_RATIO"),//成功借款次数和申请次数占比
    MULTI_OVERDUE_COUNT(1350003,"MULTI_OVERDUE_COUNT"),//逾期次数
    MULTI_OVERDUE_SUCCESS_RATIO(1350004,"MULTI_OVERDUE_SUCCESS_RATIO"),//逾期次数与成功借款次数占比
    MULTI_AVERAGE_OVERDUE_DAYS(1350005,"MULTI_AVERAGE_OVERDUE_DAYS"),//平均逾期天数
    MULTI_LOAN_INTERVAL_DAYS(1350006,"MULTI_LOAN_INTERVAL_DAYS"),//平均借款间隔天数
    MULTI_OVERDUE1_COUNT(1350007,"MULTI_OVERDUE1_COUNT"),//逾期1天的次数
    MULTI_OVERDUE2_COUNT(1350008,"MULTI_OVERDUE2_COUNT"),//逾期2天的次数
    MULTI_OVERDUE3_COUNT(1350009,"MULTI_OVERDUE3_COUNT"),//逾期3天的次数
    MULTI_OVERDUE4_COUNT(1350010,"MULTI_OVERDUE4_COUNT"),//逾期4天的次数
    MULTI_OVERDUE5_COUNT(1350011,"MULTI_OVERDUE5_COUNT"),//逾期5天的次数
    MULTI_OVERDUE6_COUNT(1350012,"MULTI_OVERDUE6_COUNT"),//逾期6天的次数
    MULTI_OVERDUE_MORE_THAN6_COUNT(1350013,"MULTI_OVERDUE_MORE_THAN6_COUNT"),//逾期6天以上次数
    MULTI_OVERDUE1_RATIO(1350014,"MULTI_OVERDUE1_RATIO"),//逾期1天的占比
    MULTI_OVERDUE2_RATIO(1350015,"MULTI_OVERDUE2_RATIO"),//逾期2天的占比
    MULTI_OVERDUE3_RATIO(1350016,"MULTI_OVERDUE3_RATIO"),//逾期3天的占比
    MULTI_OVERDUE4_RATIO(1350017,"MULTI_OVERDUE4_RATIO"),//逾期4天的占比
    MULTI_OVERDUE5_RATIO(1350018,"MULTI_OVERDUE5_RATIO"),//逾期5天的占比
    MULTI_OVERDUE6_RATIO(1350019,"MULTI_OVERDUE6_RATIO"),//逾期6天的占比
    MULTI_OVERDUE_MORE_THAN6_RATIO(1350020,"MULTI_OVERDUE_MORE_THAN6_RATIO"),//逾期6天以上占比


    //20181031
    GOJEK_EMAIL_NOT_SAME_AND_MOBILE_NOT_SAME(1360001,"GOJEK_EMAIL_NOT_SAME_AND_MOBILE_NOT_SAME"),//gojek邮箱是不一致&gojek手机号是不一致
    HOUSE_WIFE_AND_MARRIAGE_STATUS(1360002,"HOUSE_WIFE_AND_MARRIAGE_STATUS"),//身份是家庭主妇但婚姻状态是非已婚
    SAME_DAY_SAME_IP(1360003,"SAME_DAY_SAME_IP"),//同一天内同一个IP的申请次数
    FACEBOOK_AVERAGE_MONTH_COMMENT_FEMALE(1360004,"FACEBOOK_AVERAGE_MONTH_COMMENT_FEMALE"),//facebook月均评论数&女
    SEX_MARRIAGE_EDUCATION(1360005,"SEX_MARRIAGE_EDUCATION"),//性别&婚姻状态&学历 //男&单身&高中及以下
    FACEBOOK_AVERAGE_MONTH_POST_MALE(1360006,"FACEBOOK_AVERAGE_MONTH_POST_MALE"),//facebook月均帖子数&男
    HIT_COLLECTOR_BLACK_LIST(1340007,"HIT_COLLECTOR_BLACK_LIST"),//命中催收黑名单用户身份证号或手机号
    MULTI_HIT_COLLECTOR_BLACK_LIST(1340004,"MULTI_HIT_COLLECTOR_BLACK_LIST"),//命中催收黑名单用户身份证号或手机号

    SPECIAL_RULE_100_RMB_PRODUCT(1350001,"SPECIAL_RULE_100_RMB_PRODUCT"),//订单二次审核通过100rmb规则

    //100rmb
    WORK_ADDRESS_INVALID_100RMB(1360001,"WORK_ADDRESS_INVALID_100RMB"),//工作地址不属于雅加达大区和爪哇岛和巴厘岛-100RMB
    COMB_SAMEIPCOUNT_600RMB(1360002,"COMB_SAMEIPCOUNT_600RMB"),//同一天内同一个IP的申请次数&男-100RMB
    NIGHT_CALL_RATE_100RMB(1360003,"NIGHT_CALL_RATE_100RMB"),//近30天内夜间活跃占比-100RMB
    RECENT30_EVENING_CALL_RATE_MALE_100RMB(1360003,"RECENT30_EVENING_CALL_RATE_MALE_100RMB"),//近30天内夜间活跃占比&男-100RMB

    //20181129
    TOTAL_MEMORY_APPLY_TIME_HOUR(1370001,"TOTAL_MEMORY_APPLY_TIME_HOUR"),//手机总内存&提交时间
    FEMALE_AGE_CHILDREN_COUNT(1370002,"FEMALE_AGE_CHILDREN_COUNT"),//女性&年龄&孩子数量
    MALE_AGE_CHILDREN_COUNT_EDUCATION(1370003,"MALE_AGE_CHILDREN_COUNT_EDUCATION"),//男性&年龄&孩子数量&学历

    NO_TAX_NUMBER_NO_PAYROLL_POST_MALE(1370003,"NO_TAX_NUMBER_NO_PAYROLL_POST_MALE"),//无税卡&未上传工资单&特定职业&男性[]

    //20181201
    TOTAL_MEMORY_COMPANY_CALL_BANK_CODE_MALE(1380001,"TOTAL_MEMORY_COMPANY_CALL_BANK_CODE_MALE"),//手机总内存&外呼公司电话返回结果&特定银行&男
    MALE_AGE(1380002,"MALE_AGE"),//男性年龄不符
    MALE_EDUCATION(1380003,"MALE_EDUCATION"),//性别&学历不符//男性&学历为高中
    MALE_NOTAXNUMBER(1380004,"MALE_NOTAXNUMBER"),//性别&未提交税卡//男性&未提交税卡
    WORK_ADDRESS_NOT_VALID_NORMAL(1380004,"WORK_ADDRESS_NOT_VALID_NORMAL"),//工作城市不佳

    //20181205
    NO_TAXNUMBER_APP_COUNT(1390001,"NO_TAXNUMBER_APP_COUNT"),//无税卡&首借累计APP个数
    GOJEK_CASH_PAY_COUNT(1390002,"GOJEK_CASH_PAY_COUNT"),//现金支付次数
    GOJEK_SAME_MOBILE_SAME_EMAIL_SAME_ADDRESS_FEMALE(1390003,"GOJEK_SAME_MOBILE_SAME_EMAIL_SAME_ADDRESS_FEMALE"),//gojek手机号一致&gojek邮箱一致&乘车地匹配公司地址同时出现&性别
    LANGUAGE_MONTHLY_SALARY(1390004,"LANGUAGE_MONTHLY_SALARY"),//手机语言&月收入
    WORK_ADDRESS_NOT_VALID_NORMAL_IOS(1390005,"WORK_ADDRESS_NOT_VALID_NORMAL_IOS"),//工作城市不佳，针对iOS

    //20181220
    IZI_PHONEAGE_PHONEVERIFY_APPCOUNT_LANGUAGE(1400001,"IZI_PHONEAGE_PHONEVERIFY_APPCOUNT_LANGUAGE"),//IZI在网时长&IZI手机实名认证&首借累计APP个数&手机语言
    IZI_PHONEAGE_PHONEVERIFY_APPCOUNT_LANGUAGE_100(1400001,"IZI_PHONEAGE_PHONEVERIFY_APPCOUNT_LANGUAGE_100"),//IZI在网时长&IZI手机实名认证&首借累计APP个数&手机语言
    MALE_APPCOUNT_MONTH_SALARY_IZI_PHONEAGE_PHONEVERIFY(1400002,"MALE_APPCOUNT_MONTH_SALARY_IZI_PHONEAGE_PHONEVERIFY"),//男性&首借累计App个数&月收入&IZI在网时长&IZI实名
    FEMALE_APPCOUNT_MONTH_SALARY_IZI_PHONEAGE_PHONEVERIFY(1400003,"FEMALE_APPCOUNT_MONTH_SALARY_IZI_PHONEAGE_PHONEVERIFY"),//女性&首借累计App个数&月收入&IZI在网时长&IZI实名

    //20181229
    COMPANY_CALL_IOS_FEMALE(1500001,"COMPANY_CALL_IOS_FEMALE"),//公司外呼&IOS&女性
    COMPANY_CALL_IOS_MALE_MONTHLY_INCOME(1500002,"COMPANY_CALL_IOS_MALE_MONTHLY_INCOME"),//公司外呼&IOS&男性&月收入
    TOTAL_MEMORY_APPLY_TIME_HOUR_MALE(1500003,"TOTAL_MEMORY_APPLY_TIME_HOUR_MALE"),//手机总内存&下单时间&男性

    //20190103
    TOTAL_MOBILE_CAP_MALE(1600001,"TOTAL_MOBILE_CAP_MALE"),//手机总容量&男性_600
    MALE_NO_TAXNUMBER_APPCOUNT(1600002,"MALE_NO_TAXNUMBER_APPCOUNT"),//男性&无税卡&首借累计app个数_100
    MALE_EDUCATION_MARRIAGE_APPLY_TIME_HOUR(1600004,"MALE_EDUCATION_MARRIAGE_APPLY_TIME_HOUR"),//男性&学历&单身&下单时间_100
    APPCOUNT_MALE(1600005,"APPCOUNT_MALE"),//累计App个数&男性
    APPLY_TIME_HOUR_MALE(1600006,"APPLY_TIME_HOUR_MALE"),//下单时间在凌晨0-5点&男性

    CAP_MONTHLY_INCOME_GOJEK_MOBILE_NOT_SAME(1600007,"CAP_MONTHLY_INCOME_GOJEK_MOBILE_NOT_SAME"),//手机总容量&收入&gojek手机号不一致
    CAP_MARRIAGE_FEMALE_GOJEK_MOBILE_NOT_SAME(1600008,"CAP_MARRIAGE_FEMALE_GOJEK_MOBILE_NOT_SAME"),//手机总容量&婚姻&性别&gojek手机号不一致

    FLOW_MAX_ISSUED_LIMIT(1600009,"FLOW_MAX_ISSUED_LIMIT"),//超过该流程放款数量

    //20190108
    MOBILE_LANGUAGE_MALE_APPLY_TIME_HOUR(1700001,"MOBILE_LANGUAGE_MALE_APPLY_TIME_HOUR"),//手机语言&性别&提交时间

    MOBILE_LANGUAGE_MALE_APPLY_TIME_HOUR_100RMB(1700005,"MOBILE_LANGUAGE_MALE_APPLY_TIME_HOUR_100RMB"),//手机语言&性别&提交时间_100RMB

    IZI_PHONEAGE_PHONEVERIFY_EDUCATION_MONTHLY_INCOME_FEMALE(1700002,"IZI_PHONEAGE_PHONEVERIFY_EDUCATION_MONTHLY_INCOME_FEMALE"),//IZI在网时长&IZI手机实名&学历&月收入&女性
    IZI_PHONEAGE_PHONEVERIFY_MEMORY_MALE(1700003,"IZI_PHONEAGE_PHONEVERIFY_MEMORY_MALE"),//IZI在网时长&IZI手机实名认证&手机总内存&男性
    IZI_PHONEAGE_PHONEVERIFY_MOBILE_LANGUAGE_COMPANY_CALL(1700004,"IZI_PHONEAGE_PHONEVERIFY_MOBILE_LANGUAGE_COMPANY_CALL"),//IZI在网时长&IZI手机实名认证&语言&公司外呼


    //20190110
    MONTHLY_INCOME_GOJEK_MAX_DISTANCE_FEMALE(1800001,"MONTHLY_INCOME_GOJEK_MAX_DISTANCE_FEMALE"),//月收入&单次乘车最长距离&性别
    COMPANY_TEL_COMPANY_NAME_MALE(1800002,"COMPANY_TEL_COMPANY_NAME_MALE"),//公司号码&公司名称&性别


     //20190114
    WHATSAPP_SAME_WITH_MOBILE_FEMALE_AGE_EDUCATION(1800003,"WHATSAPP_SAME_WITH_MOBILE_FEMALE_AGE_EDUCATION"),//whatsapp账号是否一致&性别&年龄&学历

    //remark
    WHATSAPP_IN_OVERDUE7_BLACKLIST(1800004,"WHATSAPP_IN_OVERDUE7_BLACKLIST"),//申请人的va号码命中逾期7天用户的号码
    WHATSAPP_IN_OVERDUE7_EMERGENCY_LINKMAN(1800004,"WHATSAPP_IN_OVERDUE7_EMERGENCY_LINKMAN"),//申请人的va号码命中逾期7天用户紧急联系人
    WHATSAPP_IN_OVERDUE7_CALL_RECORDS(1800004,"WHATSAPP_IN_OVERDUE7_CALL_RECORDS"),//申请人的va号码命中逾期7天用户通话记录
    WHATSAPP_IN_OVERDUE7_CONTACTS(1800004,"WHATSAPP_IN_OVERDUE7_CONTACTS"),//申请人的va号码命中逾期7天用户通讯录
    WHATSAPP_IN_OVERDUE7_SHORTMESSAGE(1800004,"WHATSAPP_IN_OVERDUE7_SHORTMESSAGE"),//申请人的va号码命中逾期7天用户的短信
    EMERGENCY_LINKMAN_IN_FRAUD_USER_EMERGENCY_LINKMAN(1800004,"EMERGENCY_LINKMAN_IN_FRAUD_USER_EMERGENCY_LINKMAN"),//申请人的紧急联系人号码命中欺诈用户的紧急联系人
    EMERGENCY_LINKMAN_IN_FRAUD_USER_CALL_RECORDS(1800004,"EMERGENCY_LINKMAN_IN_FRAUD_USER_CALL_RECORDS"),//申请人的紧急联系人号码命中欺诈用户的通话记录
    EMERGENCY_LINKMAN_IN_FRAUD_USER_CONTACTS(1800004,"EMERGENCY_LINKMAN_IN_FRAUD_USER_CONTACTS"),//申请人的紧急联系人号码命中欺诈用户的通讯录
    EMERGENCY_LINKMAN_IN_FRAUD_USER_SHORTMESSAGE(1800004,"EMERGENCY_LINKMAN_IN_FRAUD_USER_SHORTMESSAGE"),//申请人的紧急联系人号码命中欺诈用户的短信
    EMERGENCY_LINKMAN_IN_FRAUD_USER_WHATSAPP(1800004,"EMERGENCY_LINKMAN_IN_FRAUD_USER_WHATSAPP"),//申请人的紧急联系人号码命中欺诈用户的va

    COMPANY_TEL_IN_OVERDUE7_BLACKLIST(1800004,"COMPANY_TEL_IN_OVERDUE7_BLACKLIST"),//申请人公司电话命中逾期7天用户的公司电话
    COMPANY_ADDRESS_IN_OVERDUE7_BLACKLIST(1800004,"COMPANY_ADDRESS_IN_OVERDUE7_BLACKLIST"),//申请人公司地址命中逾期7天用户的公司地址
    HOME_ADDRESS_IN_OVERDUE7_BLACKLIST(1800004,"HOME_ADDRESS_IN_OVERDUE7_BLACKLIST"),//申请人居住地址命中逾期7天用户的居住地址

    COMPANY_TEL_IN_FRAUD_USER_BLACKLIST(1800004,"COMPANY_TEL_IN_FRAUD_USER_BLACKLIST"),//申请人公司电话命中欺诈用户的公司电话
    COMPANY_ADDRESS_IN_FRAUD_USER_BLACKLIST(1800004,"COMPANY_ADDRESS_IN_FRAUD_USER_BLACKLIST"),//申请人公司地址命中逾期7天用户的公司地址
    HOME_ADDRESS_IN_FRAUD_USER_BLACKLIST(1800004,"HOME_ADDRESS_IN_FRAUD_USER_BLACKLIST"),//申请人居住地址命中逾期7天用户的居住地址

    //20190116
    COMPANY_TEL_MALE(1900001,"COMPANY_TEL_MALE"),//公司外呼and性别
    COMPANY_TEL_MALE_MONTHLY_INCOME(1900001,"COMPANY_TEL_MALE_MONTHLY_INCOME"),//公司外呼and性别and月收入
    //公司外呼and性别&月收入&学历&孩子数量
    COMPANY_TEL_MALE_MONTHLY_INCOME_EDUCATION_CHILDREN_COUNT(1900001,"COMPANY_TEL_MALE_MONTHLY_INCOME_EDUCATION_CHILDREN_COUNT"),

    INSTALLPED_APP_DIFFDAYS_OF_LASTEST_COMMIT_TIME(1900001,"INSTALLPED_APP_DIFFDAYS_OF_LASTEST_COMMIT_TIME"),//APP最后一次更新时间距提交的天数
    INSTALLPED_APP_DIFFDAYS_OF_EARLIEST_COMMIT_TIME(1900001,"INSTALLPED_APP_DIFFDAYS_OF_EARLIEST_COMMIT_TIME"),//APP最早一次更新时间距提交的天数
    INSTALLPED_APP_DIFFDAYS_OF_EARLIEST_LATEST_TIME(1900001,"INSTALLPED_APP_DIFFDAYS_OF_EARLIEST_LATEST_TIME"),//APP最后一次更新时间-最早一次更新时间

    //2018-01-18 app 分类相关规则
    APP_COUNT_FOR_NEWS(2000001, "APP_COUNT_FOR_NEWS"),//新闻类app个数
    APP_COUNT_FOR_ENTERPRISE(2000002, "APP_COUNT_FOR_ENTERPRISE"),//企业类app个数
    APP_COUNT_FOR_BEAUTY(2000003, "APP_COUNT_FOR_BEAUTY"),//美容类app个数
    APP_COUNT_FOR_GAMBLING(2000004, "APP_COUNT_FOR_GAMBLING"),//赌博类app个数
    APP_COUNT_FOR_CREDIT_CARD(2000005, "APP_COUNT_FOR_CREDIT_CARD"),//信用卡类app个数
    APP_COUNT_FOR_BEAUTY_PICTURE(2000006, "APP_COUNT_FOR_BEAUTY_PICTURE"),//美图类app个数
    APP_COUNT_FOR_PHOTOGRAPHY(2000007, "APP_COUNT_FOR_PHOTOGRAPHY"),//摄影类app个数
    APP_COUNT_FOR_E_COMMERCE(2000008, "APP_COUNT_FOR_E_COMMERCE"),//电商类app个数
    APP_COUNT_FOR_GAME(2000009, "APP_COUNT_FOR_GAME"),//游戏类app个数
    APP_COUNT_FOR_SOCIAL(2000010, "APP_COUNT_FOR_SOCIAL"),//社交类app个数
    APP_COUNT_FOR_TAX_BPJS(2000011, "APP_COUNT_FOR_TAX_BPJS"),//税卡和bpjs
    APP_COUNT_FOR_BANK(2000012, "APP_COUNT_FOR_BANK"),//银行类app个数
    APP_COUNT_FOR_CINEMA(2000013, "APP_COUNT_FOR_CINEMA"),//电影院类app个数
    APP_COUNT_FOR_TICKET(2000014, "APP_COUNT_FOR_TICKET"),//票务类app个数

    //custom device fingerprint
    SAME_IMSI(2010001,"SAME_IMSI"),//imsi相同数量
    CUSTOM_DEVICE_FINGER_PRINT_APPS(2010001,"CUSTOM_DEVICE_FINGER_PRINT_APPS"),//app相关自定义设备指纹
    CUSTOM_DEVICE_FINGER_PRINT_PHONE_BRAND(2010001,"CUSTOM_DEVICE_FINGER_PRINT_PHONE_BRAND"),//ip相关自定义设备指纹
    CUSTOM_DEVICE_FINGER_PRINT_IP(2010001,"CUSTOM_DEVICE_FINGER_PRINT_IP"),//ip相关自定义设备指纹
    CUSTOM_DEVICE_FINGER_PRINT_DEVICE_NAME_MEMORY_CPU(2010001,"CUSTOM_DEVICE_FINGER_PRINT_DEVICE_NAME_MEMORY_CPU"),//androidId & deviceName & totalMemory & cpuType
    CUSTOM_DEVICE_FINGER_PRINT_MAC_ADDRESS_WITHOUT_ANDROIDID(2010001,"CUSTOM_DEVICE_FINGER_PRINT_MAC_ADDRESS_WITHOUT_ANDROIDID"),//无android的其他组合


    //20190124

    //IZI手机实名认证&年龄&性别
    REBORROWING_IZI_PHONEVERIFY_AGE_MALE(2020001,"REBORROWING_IZI_PHONEVERIFY_AGE_MALE"),
    //公司外呼&总内存
    REBORROWING_FIRST_LOAN_COMPANY_CALL_TOTAL_MEMORY(2020002,"REBORROWING_FIRST_LOAN_COMPANY_CALL_TOTAL_MEMORY"),
    //IZI手机在网时长&IZI手机实名认证_'NOT_MATCH'&性别
    REBORROWING_IZI_PHONEAGE_PHONEVERIFY_MALE(2020002,"REBORROWING_IZI_PHONEAGE_PHONEVERIFY_MALE"),

    IZI_PHONEVERIFY_LANGUAGE_AGE_MALE(2020002,"IZI_PHONEVERIFY_LANGUAGE_AGE_MALE"),//IZI手机实名认证&男性&语言&年龄
    IZI_PHONEVERIFY_LANGUAGE_AGE_MALE_100(2020002,"IZI_PHONEVERIFY_LANGUAGE_AGE_MALE_100"),//IZI手机实名认证&男性&语言&年龄
    //女性&学历&电商类APP个数&联系人外呼完全有效占比
    EDUCATION_APPCOUNT_FOR_ECOMMERCE_LINKMAN_CALL_RESULT_FEMALE(2020002,"EDUCATION_APPCOUNT_FOR_ECOMMERCE_LINKMAN_CALL_RESULT_FEMALE"),
    //男性&学历&电商类APP个数&公司外呼
    EDUCATION_APPCOUNT_FOR_ECOMMERCE_COMPANY_CALL_RESULT_MALE(2020002,"EDUCATION_APPCOUNT_FOR_ECOMMERCE_COMPANY_CALL_RESULT_MALE"),


    //20190301
    //婚姻&年龄下限
    MARITALSTATUS_AGE(2030001,"MARITALSTATUS_AGE"),
    //电商类app个数&月收入&性别
    APP_COUNT_FOR_E_COMMERCE_MONTHLY_SALARY_SEX(2030002,"APP_COUNT_FOR_E_COMMERCE_MONTHLY_SALARY_SEX"),
    //whatsapp账号不是本人手机号&男性&年龄
    WHATSAPP_NOT_MOBILE_SEX_AGE(2030003, "WHATSAPP_NOT_MOBILE_SEX_AGE"),



    //20190304
    FEMALE_EDUCATION_CREDIT_CARD_COMPANY_TEL_IZI_PHONEVERIFY(2040001,"FEMALE_EDUCATION_CREDIT_CARD_COMPANY_TEL_IZI_PHONEVERIFY"),
    MALE_EDUCATION_CREDIT_CARD_COMPANY_TEL_AGE(2040002,"MALE_EDUCATION_CREDIT_CARD_COMPANY_TEL_AGE"),
    MALE_CREDIT_CARD_MONTHLY_SALARY_COMPANY_TEL(2040003,"MALE_CREDIT_CARD_MONTHLY_SALARY_COMPANY_TEL"),
    MALE_CREDIT_CARD_MONTHLY_SALARY_COMPANY_TEL_IZI_PHONEVERIFY(2040004,"MALE_CREDIT_CARD_MONTHLY_SALARY_COMPANY_TEL_IZI_PHONEVERIFY"),
    MALE_CREDIT_CARD_MONTHLY_SALARY_IZI_PHONEVERIFY(2040005,"MALE_CREDIT_CARD_MONTHLY_SALARY_IZI_PHONEVERIFY"),
    MALE_CREDIT_CARD_MONTHLY_SALARY_COMPANY_TEL_IZI_PHONEVERIFY_01(2040006,"MALE_CREDIT_CARD_MONTHLY_SALARY_COMPANY_TEL_IZI_PHONEVERIFY_01"),


    //20190307
    ID_CARD_BIRTHDAY_NOT_SAME_WITH_USER_DETAIL(2050001, "ID_CARD_BIRTHDAY_NOT_SAME_WITH_USER_DETAIL"),//身份证号对应的生日与用户填写的不一致
    ID_CARD_SEX_NOT_SAME_WITH_USER_DETAIL(2050002, "ID_CARD_SEX_NOT_SAME_WITH_USER_DETAIL"),//身份证号对应的性别与用户填写的不一致


    //20190308
    CREDIT_CARD_ECOMMERCE_MALE_EDUCATION(2060001,"CREDIT_CARD_ECOMMERCE_MALE_EDUCATION"),
    TOTAL_APP_COUNT_MALE_IZI_PHONEVERIFY(2060002,"TOTAL_APP_COUNT_MALE_IZI_PHONEVERIFY"),


    //20190314
    EMERGENCY_TEL_IN_FIRST_BORROW_600_IZI_PHONEVERIFY(2070001,"EMERGENCY_TEL_IN_FIRST_BORROW_600_IZI_PHONEVERIFY"),
    HISTORY_SUBMIT_COUNT_MALE(2070002,"HISTORY_SUBMIT_COUNT_MALE"),

    //20190314
    MALE_IZI_PHONEVERIFY_PHONEAGE(2080001,"MALE_IZI_PHONEVERIFY_PHONEAGE"),
    MALE_IZI_PHONEVERIFY_PHONEAGE_AGE(2080002,"MALE_IZI_PHONEVERIFY_PHONEAGE_AGE"),
    MALE_MONTHLY_INCOME_AGE_EDUCATION_HAS_CREDIT_CARD(2080003,"MALE_MONTHLY_INCOME_AGE_EDUCATION_HAS_CREDIT_CARD"),

    NO_GOJEK_IZI_PHONEAGE_AGE_MALE(2080004,"NO_GOJEK_IZI_PHONEAGE_AGE_MALE"),
    NO_GOJEK_IZI_PHONEAGE_FEMALE_WHATSAPP_MOBILE_NOT_SAME(2080005,"NO_GOJEK_IZI_PHONEAGE_FEMALE_WHATSAPP_MOBILE_NOT_SAME"),
    NO_GOJEK_IZI_PHONEAGE_MALE_EDUCATION(2080006,"NO_GOJEK_IZI_PHONEAGE_MALE_EDUCATION"),
    NO_GOJEK_IZI_PHONEAGE_FEMALE_EDUCATION(2080007,"NO_GOJEK_IZI_PHONEAGE_FEMALE_EDUCATION"),


    //20190319
    MALE_MARRIAGE_EDUCATION_DRIVER_LICENSE(2090001,"MALE_MARRIAGE_EDUCATION_DRIVER_LICENSE"),//男性&单身&学历&年龄&未上传驾驶证
    MALE_WHATSAPP_NOT_SAME_TAX_NUMBER_AGE_MONTHLY_INCOME(2090002,"MALE_WHATSAPP_NOT_SAME_TAX_NUMBER_AGE_MONTHLY_INCOME"),//男性&WhatsApp账号不一致&提交税卡&年龄&月收入
    MALE_WHATSAPP_NOT_SAME_TAX_NUMBER(2090003,"MALE_WHATSAPP_NOT_SAME_TAX_NUMBER"),//男性&WhatsApp账号不一致&未提交税卡
    MALE_WHATSAPP_SAME_TAX_NUMBER_IZI_PHONEVERIFY_MONNTHLY_INCOME_MARRIAGE_AGE(2090004,
            "MALE_WHATSAPP_SAME_TAX_NUMBER_IZI_PHONEVERIFY_MONNTHLY_INCOME_MARRIAGE_AGE"),//男性&WhatsApp账号一致&未提交税卡&IZI手机实名NOTMATCH&月收入&单身&年龄12

    WHATSAPP_NOT_SAME_TAX_NUMBER_IZI_PHONEVERIFY_AGE(2090005,"WHATSAPP_NOT_SAME_TAX_NUMBER_IZI_PHONEVERIFY_AGE"),//WhatsApp账号一致&未提交税卡&IZI手机实名NOTFOUND&年龄


    SCORE_MODEL_PRODUCT_600(2090006,"SCORE_MODEL_PRODUCT_600"),//600产品模型分第一版

    SCORE_MODEL_PRODUCT_600_V1(2090013,"SCORE_MODEL_PRODUCT_600_V1"),//600产品模型分第一版

    //20190321
    //男性&学历&注册到提交时间&填写信息时长&未上传驾驶证&未验证gojek
    MALE_EDUCATION_DIFFMINS_OF_CREATE_SUBMIT_DIFFMINS_OF_STEP1TO2_DRIVERLICENSE_GOJEK(2090007,
            "MALE_EDUCATION_DIFFMINS_OF_CREATE_SUBMIT_DIFFMINS_OF_STEP1TO2_DRIVERLICENSE_GOJEK"),
    //whatsapp账号不是本人手机号&未验证gojek&未上传驾驶证&未上传工资单
    WHATSAPP_NOT_SAME_GOJEK_DRIVERLICENSE_PAYROLL(2090008,"WHATSAPP_NOT_SAME_GOJEK_DRIVERLICENSE_PAYROLL"),

    //男性&未验证gojek&年龄&银行
    MALE_GOJEK_AGE_BANKCODE(2090009,"MALE_GOJEK_AGE_BANKCODE"),


    //女性&未验证gojek&年龄&公司外呼&银行&cashcash
    FEMALE_GOJEK_AGE_COMP_TEL_BANK_CODE(2090010,"FEMALE_GOJEK_AGE_COMP_TEL_BANK_CODE"),
    //男性&未验证gojek&年龄&公司外呼
    MALE_GOJEK_AGE_COMP_TEL(2090011,"MALE_GOJEK_AGE_COMP_TEL"),

    //男性&学历&借款用途&未上传驾驶证&未验证gojek
    MALE_EDUCATION_BORROWING_PURPOSE_DRIVERLICENSE_GOJEK(2090011,"MALE_EDUCATION_BORROWING_PURPOSE_DRIVERLICENSE_GOJEK"),

    //IZI本人whatsapp未开通&男性
    WHATSAPP_CONNECT_MALE(2090014,"WHATSAPP_CONNECT_MALE"),
    WHATSAPP_CONNECT_FEMALE(2090015,"WHATSAPP_CONNECT_FEMALE"),

    //600产品分数大于女性
    SCORE_MODEL_PRODUCT_600_SEX(2090016,"SCORE_MODEL_PRODUCT_600_SEX"),
    //验证了gojek&本人whatsapp开通&联系人Whatsapp开通占比&女性
    GOJEK_WHATSAPP_WHATSAPPRATIO_SEX(2090017,"GOJEK_WHATSAPP_WHATSAPPRATIO_SEX"),

    //IZI手机实名 & whatsapp账号是本人手机号 &女性
    IZIPHONEVERIFY_WHATSAPPANDOWNERTELSAME_SEX(2090018,"IZIPHONEVERIFY_WHATSAPPANDOWNERTELSAME_SEX"),

    //税卡&600产品模型分&非高逾期职业&男性
    TAX_SCOREMODEL600_POSITIONNAME_MEN(2090019,"TAX_SCOREMODEL600_POSITIONNAME_MEN"),
    //税卡&600产品模型分&非高逾期职业&女性
    TAX_SCOREMODEL600_POSITIONNAME_FEMAL(2090020,"TAX_SCOREMODEL600_POSITIONNAME_FEMAL"),
    //电商类APP个数&IZI实名&IZI在网时长&年龄&性别
    APPCOUNT_FOR_ECOMMERCE_IZINAME_IZIONLINETIME_AGE_SEX(2090021,"APPCOUNT_FOR_ECOMMERCE_IZINAME_IZIONLINETIME_AGE_SEX"),

    //居住地（省）高风险&男性&600产品模型分
    HOME_PROVINCE_MALE_PRODUCT600(2090022, "HOME_PROVINCE_MALE_PRODUCT600"),
    //居住地（省）高风险&女性&600产品模型分
    HOME_PROVINCE_FEMALE_PRODUCT600(2090023, "HOME_PROVINCE_FEMALE_PRODUCT600"),


    //20190419
    SEX_BORROWING_PURPOSE_AGE_APPCOUNTOFCREDIT(2100001,"SEX_BORROWING_PURPOSE_AGE_APPCOUNTOFCREDIT"),
    SEX_ORDER_ADDRESS_FIRST_EMERGENCY(2100002,"SEX_ORDER_ADDRESS_FIRST_EMERGENCY"),
    SEX_COMPANY_TEL_EMAIL(2100003,"SEX_COMPANY_TEL_EMAIL"),


    MULTI_HIT_COMPLAINT_USER_INFO(2100006,"MULTI_HIT_COMPLAINT_USER_INFO"),//命中投诉人员身份证号或手机号-复借
    HIT_COMPLAINT_USER_INFO(2100007,"HIT_COMPLAINT_USER_INFO"),//命中投诉人员身份证号或手机号
    COMPANY_NAME_BELONG_TO_ARMY(2100008,"COMPANY_NAME_BELONG_TO_ARMY"),//公司名称包含军人警察
    SAME_BANK_CARD_COUNT(2100009,"SAME_BANK_CARD_COUNT"),//相同银行卡命中多人
    EMERGENCY_TEL_IN_MULTI_USER_BANK_CARD(2100010,"EMERGENCY_TEL_IN_MULTI_USER_BANK_CARD"),//申请人任意联系人号码命中’相同银行卡命中多人‘用户手机号
    MOBILE_IN_MULTI_USER_BANK_CARD_EMERGENCY_TEL(2100011,"MOBILE_IN_MULTI_USER_BANK_CARD_EMERGENCY_TEL"),//申请人手机号命中'相同银行卡命中多人‘用户的任意联系人号码


    //居住地（省）高风险&男性&600产品模型分(150产品）
    HOME_PROVINCE_MALE_PRODUCT600_150(2090024, "HOME_PROVINCE_MALE_PRODUCT600_150"),
    //居住地（省）高风险&女性&600产品模型分
    HOME_PROVINCE_FEMALE_PRODUCT600_150(2090025, "HOME_PROVINCE_FEMALE_PRODUCT600_150"),

    //居住地（省）高风险&男性&600产品模型分(80产品）
    HOME_PROVINCE_MALE_PRODUCT600_80(2090026, "HOME_PROVINCE_MALE_PRODUCT600_80"),

    //20190426
    RISK_SCORE_600_FOR_PRD100(2100012,"RISK_SCORE_600_FOR_PRD100"), //600产品评分<=430,拒绝处理
    RISK_SCORE_100_FOR_PRD100_MALE(2100013,"RISK_SCORE_100_FOR_PRD100_MALE"), //男性&100产品评分<=675,拒绝处理
    RISK_SCORE_100_FOR_PRD100_FEMALE(2100014,"RISK_SCORE_100_FOR_PRD100_FEMALE"), //女性&100产品评分<=665,拒绝处理

    RISK_SCORE_600_FOR_PRD50_MALE(2100015,"RISK_SCORE_600_FOR_PRD50_MALE"), //男性&600产品评分<=430,拒绝处理
    RISK_SCORE_600_FOR_PRD50_FEMALE(2100016,"RISK_SCORE_600_FOR_PRD50_FEMALE"), //女性&600产品模型分<=425
    IZIPHONEAGE(2100017,"IZIPHONEAGE"),//IZI手机在网时长返回值为 PHONENUMBER_NOT_FOUND

    //下单的小区为空&600模型分&男性
    ORDERSMALLDIRECT_RISK_SCORE_600_MEAL(2100018,"ORDERSMALLDIRECT_RISK_SCORE_600_MEAL"),
    //下单的小区为空&600模型分&女性
    ORDERSMALLDIRECT_RISK_SCORE_600_FEMEAL(2100019,"ORDERSMALLDIRECT_RISK_SCORE_600_FEMEAL"),

    //男性+IZI实名认证为非match+600产品评分<=460+IZI在网时长
    MEAL_IZINOTMATCH_RISK_SCORE_600_IZITIMELONG(2100020,"MEAL_IZINOTMATCH_RISK_SCORE_600_IZITIMELONG"),
    //女性+IZI实名认证为非match+IZI在网时长
    FEMEAL_IZINOTMATCH_IZITIMELONG(2100021,"FEMEAL_IZINOTMATCH_IZITIMELONG"),
    //男性+600产品评分<=490+IZI在网时长
    MEALRISK_SCORE_600_IZITIMELONG(2100022,"MEALRISK_SCORE_600_IZITIMELONG"),

    //IZI在网时长V2版
    IZI_ONLINETIMEV2(21000213,"IZI_ONLINETIMEV2"),
    //IZI在网时长V2版&IZI手机实名
    IZI_ONLINETIMEV2_IZIPHONEREALNAME(2100024,"IZI_ONLINETIMEV2_IZIPHONEREALNAME"),


    //advance黑名单多头规则20190506
    ADVANCE_BLACKLIST(2100025,"ADVANCE_BLACKLIST"),
    ADVANCE_MULTI_PLATFORM(2100025,"ADVANCE_MULTI_PLATFORM"),


    //20190521
    MOBILE_IS_EMERGENCYTEL_FOR_OVERDUELESSTHAN5_USERS_IZI_SEX(21100003,"MOBILE_IS_EMERGENCYTEL_FOR_OVERDUELESSTHAN5_USERS_IZI_SEX"),

    //20190524
    MALE_IZI_WHATSAPP_RESULT(21100004, "MALE_IZI_WHATSAPP_RESULT"),
    FEMALE_IZI_WHATSAPP_IZI_PHONEVERIFY(21100005, "FEMALE_IZI_WHATSAPP_IZI_PHONEVERIFY"),
    FEMALE_IZI_WHATSAPP_IZI_PHONEVERIFY_IZI_LINKMAN_WHATSAPP(21100006, "FEMALE_IZI_WHATSAPP_IZI_PHONEVERIFY_IZI_LINKMAN_WHATSAPP"),


    //20190528
    APPLY_TIME_MALE_IZI_PHONEVERIFY(21200001,"APPLY_TIME_MALE_IZI_PHONEVERIFY"),
    RISK_SCORE_600_V2_MALE(21200002,"RISK_SCORE_600_V2_MALE"),
    RISK_SCORE_600_V2_FEMALE(21200003,"RISK_SCORE_600_V2_FEMALE"),
    RISK_SCORE_600_V2_FEMALE_IZI_PHONEVERIFY(21200004,"RISK_SCORE_600_V2_FEMALE_IZI_PHONEVERIFY"),


    //20190531
    ORDER_SMALL_DIRECT(21300001,"ORDER_SMALL_DIRECT"),
    SAME_DEVICE_LINKMAN(21300002,"SAME_DEVICE_LINKMAN"),

    //20190610
    MOBILE_IS_EMERGENCYTEL_FOR_1THORDER_OVERDUE7_USER(21400001,"MOBILE_IS_EMERGENCYTEL_FOR_1THORDER_OVERDUE7_USER") ,//申请人手机号是首借逾期7天及以上用户的联系人号码
    EMERGENCYTEL_IS_EMERGENCYTEL_FOR_1THORDER_OVERDUE7_USER(21400002,"EMERGENCYTEL_IS_EMERGENCYTEL_FOR_1THORDER_OVERDUE7_USER") ,//申请人联系人号码是首借逾期7
    // 天及以上用户的联系人号码
    EMERGENCYTEL_IS_1THORDER_OVERDUE7_USER(21400003,"EMERGENCYTEL_IS_1THORDER_OVERDUE7_USER") ,//申请人联系人号码是首借逾期7天及以上用户的本人号码

    MOBILE_IS_EMERGENCYTEL_FOR_2THORDER_OVERDUE7_USER(21400004,"MOBILE_IS_EMERGENCYTEL_FOR_2THORDER_OVERDUE7_USER") ,//申请人手机号是第2笔逾期7天及以上用户的联系人号码
    EMERGENCYTEL_IS_EMERGENCYTEL_FOR_2THORDER_OVERDUE7_USER(21400005,"EMERGENCYTEL_IS_EMERGENCYTEL_FOR_2THORDER_OVERDUE7_USER") ,//申请人联系人号码是第2笔逾期7
    // 天及以上用户的联系人号码
    EMERGENCYTEL_IS_2THORDER_OVERDUE7_USER(21400006,"EMERGENCYTEL_IS_2THORDER_OVERDUE7_USER") ,//申请人联系人号码是第2笔逾期7天及以上用户的本人号码

    EMERGENCYTEL_IS_EMERGENCYTEL_FOR_3THOR4THORDER_OVERDUE7_USER(21400007,"EMERGENCYTEL_IS_EMERGENCYTEL_FOR_3THOR4THORDER_OVERDUE7_USER"),
    //申请人联系人号码是第3，4笔逾期7天及以上用户的联系人号码


    SAME_LINKMAN_WITH_SETTLED_ORDER(21400008, "SAME_LINKMAN_WITH_SETTLED_ORDER"),//任意一个联系人相同
    SAME_LINKMAN_WITHOUT_SUCCESS_ORDER(21400009, "SAME_LINKMAN_WITHOUT_SUCCESS_ORDER"),//任意一个联系人相同

    //20190620
    //男性&电商类app个数&信用卡类app个数&IZI在网时长&未验证gojek&50产品模型评分
    MALE_ECOMMERCE_CREDIT_CARD_APPCOUNT_IZIPHONEAGE_GOJEK_MODEL50SCORE(21500001,"MALE_ECOMMERCE_CREDIT_CARD_APPCOUNT_IZIPHONEAGE_GOJEK_MODEL50SCORE"),
    //男性&电商类app个数&信用卡类app个数&IZI实名认证&未验证gojek&50产品模型评分
    MALE_ECOMMERCE_CREDIT_CARD_APPCOUNT_IZIPHONEVERIFY_GOJEK_MODEL50SCORE(21500002,"MALE_ECOMMERCE_CREDIT_CARD_APPCOUNT_IZIPHONEVERIFY_GOJEK_MODEL50SCORE"),


    //20190624
    FEMALE_WHATSAPP_OPEN_UPDATETIME_AVATAR(21600001,"FEMALE_WHATSAPP_OPEN_UPDATETIME_AVATAR"),
    MALE_WHATSAPP_OPEN_UPDATETIME_AVATAR(21600002,"MALE_WHATSAPP_OPEN_UPDATETIME_AVATAR"),
    FEMAIL_WHATSAPP_OPEN_UPDATETIME_AVATAR_DRIVERLICENSE(21600003,"FEMAIL_WHATSAPP_OPEN_UPDATETIME_AVATAR_DRIVERLICENSE"),
    MALE_WHATSAPP_OPEN_UPDATETIME_AVATAR_EDUCATION(21600004,"MALE_WHATSAPP_OPEN_UPDATETIME_AVATAR_EDUCATION"),

    //20190625
    MOBILE_IS_EMERGENCY_TEL_FOR_1TH_UNSETTLED_OVERDUE7USER(21700001,"MOBILE_IS_EMERGENCY_TEL_FOR_1TH_UNSETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_OWNER_FOR_1TH_UNSETTLED_OVERDUE7USER(21700002,"EMERGENCY_TEL_IS_OWNER_FOR_1TH_UNSETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_1TH_UNSETTLED_OVERDUE7USER(21700003,"EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_1TH_UNSETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_OWNER_FOR_2TH_UNSETTLED_OVERDUE7USER(21700004,"EMERGENCY_TEL_IS_OWNER_FOR_2TH_UNSETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_2TH_UNSETTLED_OVERDUE7USER(21700005,"EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_2TH_UNSETTLED_OVERDUE7USER"),
    MOBILE_IS_EMERGENCY_TEL_FOR_2TH_UNSETTLED_OVERDUE7USER(21700006,"MOBILE_IS_EMERGENCY_TEL_FOR_2TH_UNSETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_3OR4TH_UNSETTLED_OVERDUE7USER(21700007,"EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_3OR4TH_UNSETTLED_OVERDUE7USER"),

    MOBILE_IS_EMERGENCY_TEL_FOR_1TH_SETTLED_OVERDUE7USER(21700008,"MOBILE_IS_EMERGENCY_TEL_FOR_1TH_SETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_OWNER_FOR_1TH_SETTLED_OVERDUE7USER(21700009,"EMERGENCY_TEL_IS_OWNER_FOR_1TH_SETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_1TH_SETTLED_OVERDUE7USER(21700010,"EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_1TH_SETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_OWNER_FOR_2TH_SETTLED_OVERDUE7USER(21700011,"EMERGENCY_TEL_IS_OWNER_FOR_2TH_SETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_2TH_SETTLED_OVERDUE7USER(21700012,"EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_2TH_SETTLED_OVERDUE7USER"),
    MOBILE_IS_EMERGENCY_TEL_FOR_2TH_SETTLED_OVERDUE7USER(21700013,"MOBILE_IS_EMERGENCY_TEL_FOR_2TH_SETTLED_OVERDUE7USER"),
    EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_3OR4TH_SETTLED_OVERDUE7USER(21700014,"EMERGENCY_TEL_IS_EMERGENCY_TEL_FOR_3OR4TH_SETTLED_OVERDUE7USER"),

    MALE_OWNER_IZIWHATSAPP_IZIPHONEVERIFY(21700015,"MALE_OWNER_IZIWHATSAPP_IZIPHONEVERIFY"),

    //20190626
    MODEL_SCORE_FOR_PRD100(21800001, "MODEL_SCORE_FOR_PRD100"),
    HIT_NON_MANUAL_RULES(21800002, "HIT_NON_MANUAL_RULES"),
    SEX_GOJEKVERIFY_IZIPHONEVERIFY(21800003, "SEX_GOJEKVERIFY_IZIPHONEVERIFY"),
    APP_COUNT_FOR_CREDIT_CARD_PRD100(21800004, "APP_COUNT_FOR_CREDIT_CARD_PRD100"),
    SEX_IZIPHONEVERIFY_IZIPHONEAGE(21800005, "SEX_IZIPHONEVERIFY_IZIPHONEAGE"),
    RISK_SCORE_600_V2_MALE_PRD100(21200002,"RISK_SCORE_600_V2_MALE_PRD100"),
    RISK_SCORE_600_V2_FEMALE_PRD100(21200003,"RISK_SCORE_600_V2_FEMALE_PRD100"),
    SCORE_MODEL_PRODUCT_600_SEX_PRD100(21200004,"SCORE_MODEL_PRODUCT_600_SEX_PRD100"),
    MALE_ECOMMERCEAPPCOUNT_SALARY_GOJEKVERIFY(21200006, "MALE_ECOMMERCEAPPCOUNT_SALARY_GOJEKVERIFY"),
    FEMALE_EDUCATION_HASDRIVER_LICENSE(21200007, "FEMALE_EDUCATION_HASDRIVER_LICENSE"),
    MALE_EDUCATION_HASDRIVER_LICENSE_AGE(21200008, "MALE_EDUCATION_HASDRIVER_LICENSE_AGE"),
    NO_PRODUCT_100_EXTEND_RULE_HIT(21200009, "NO_PRODUCT_100_EXTEND_RULE_HIT"),


    //20190628
    // first loan amount is 150 & last loan overdue>=1 &  borrowingCount=2 & current amount = 80
    MULTI_FIRST_AMOUNT_LAST_OVERDUE_DAYS_CUR_AMOUNT_BORROWING_COUNT(21300001,
            "MULTI_FIRST_AMOUNT_LAST_OVERDUE_DAYS_CUR_AMOUNT_BORROWING_COUNT"),
    //first loan amount is 150 & last loan overdue >1 & borrowingCount>=3 & current amount = 80
    MULTI_FIRST_AMOUNT_LAST_OVERDUE_DAYS_CUR_AMOUNT_BORROWING_COUNT_N(21300002,
            "MULTI_FIRST_AMOUNT_LAST_OVERDUE_DAYS_CUR_AMOUNT_BORROWING_COUNT_N"),
    //first loan amount is 80 & borrowingCount=2 & current amount = 80
    MULTI_FIRST_AMOUNT_CUR_AMOUNT_BORROWING_COUNT(21300003,
            "MULTI_FIRST_AMOUNT_CUR_AMOUNT_BORROWING_COUNT"),
    //first loan amount is 80 & last loan overdue & borrowingCount = 2
    MULTI_FIRST_AMOUNT_LAST_OVERDUE_DAYS_BORROWING_COUNT(21300004,"MULTI_FIRST_AMOUNT_LAST_OVERDUE_DAYS_BORROWING_COUNT"),

    //20190701
    SMALL_DIRECT_MODEL_SCORE_V2_MALE(21400001,"SMALL_DIRECT_MODEL_SCORE_V2_MALE"),
    SMALL_DIRECT_MODEL_SCORE_V2_FEMALE(21400002,"SMALL_DIRECT_MODEL_SCORE_V2_FEMALE"),
    FEMALE_OWNER_WHATSAPP_CREDITCARD_APPCOUNT(21400003,"FEMALE_OWNER_WHATSAPP_CREDITCARD_APPCOUNT"),
    FEMALE_OWNER_WHATSAPP_ECOMMERCE_APPCOUNT(21400004,"FEMALE_OWNER_WHATSAPP_ECOMMERCE_APPCOUNT"),

    MALE_MODEL_SCORE_V2(21400005,"MALE_MODEL_SCORE_V2"),
    FEMALE_MODEL_SCORE_V2(21400006,"FEMALE_MODEL_SCORE_V2"),
    GOJEK_VERIFIED(21400007,"GOJEK_VERIFIED"),
    OWNER_WHATSAPP_MODEL_SCORE_V2(21400008,"OWNER_WHATSAPP_MODEL_SCORE_V2"),

    FEMALE_MODEL_SCORE_V2_TICKET_APPCOUNT_GOJEKVERIFIED(21400009,"FEMALE_MODEL_SCORE_V2_TICKET_APPCOUNT_GOJEKVERIFIED"),
    FEMALE_MODEL_SCORE_V2_TICKET_APPCOUNT_GOJEKVERIFIED_EDUCATION(21400010,"FEMALE_MODEL_SCORE_V2_TICKET_APPCOUNT_GOJEKVERIFIED_EDUCATION"),

    //连续两次复借80，并且上一笔80逾期
    MULTI_LAST_LOAN_AMOUNT_OVERDUE_CURRENT_AMOUNT_BORROWING_COUNT(21400011,"MULTI_LAST_LOAN_AMOUNT_OVERDUE_CURRENT_AMOUNT_BORROWING_COUNT"),



    //20190704
    SEX_CREDITCARD_APPCOUNT_IZI_PHONEAGE(21600001,"SEX_CREDITCARD_APPCOUNT_IZI_PHONEAGE"),
    SEX_ECOMMERCE_APPCOUNT_IZI_PHONEVERIFY_MODEL_SCORE_100(21600002,"SEX_ECOMMERCE_APPCOUNT_IZI_PHONEVERIFY_MODEL_SCORE_100"),
    SEX_SENSITIVE_APPCOUNT_MODEL_SCORE_600_V2(21600003,"SEX_SENSITIVE_APPCOUNT_MODEL_SCORE_600_V2"),

    EXCEPTION_LIST(999, "EXCEPTION_LIST"),   // 审核异常

    KEY_INfO_EMPTY(1000, "KEY_INfO_EMPTY"),   // 关键信息为空
    ;

    private BlackListTypeEnum(int type, String message) {
        this.type = type;
        this.message = message;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    private int type;

    private String message;


}
