package rules.doit.firstBorrowing;

import java.util.List;
import java.util.Arrays;
import com.yqg.drools.utils.RuleUtils;
import com.yqg.drools.model.DeviceModel;
import com.yqg.drools.model.LoanInfo;
import com.yqg.drools.model.RUserInfo;
import com.yqg.drools.model.RUserInfo.IziPhoneVerifyResult.PhoneVerifyStatusEnum;
import com.yqg.drools.model.RUserInfo.EducationEnum;
import com.yqg.drools.model.RUserInfo.MarriageEnum;
import com.yqg.drools.model.RUserInfo.IziPhoneAgeResult;
import com.yqg.drools.model.RUserInfo.IziPhoneVerifyResult;
import com.yqg.drools.model.ModelScoreResult;
import com.yqg.drools.model.InstalledAppInfo;
import com.yqg.drools.model.GojekModel;
import com.yqg.drools.model.ScoreModel;
import com.yqg.common.enums.order.BlackListTypeEnum;
import com.yqg.drools.model.base.RuleThresholdValues;
import com.yqg.drools.model.base.RuleConditionModel;


global  List ruleSetResultList;

rule "HOME_PROVINCE_MALE_PRODUCT600_A"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.HOME_PROVINCE_MALE_PRODUCT600.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.HOME_PROVINCE_MALE_PRODUCT600.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.HOME_PROVINCE_MALE_PRODUCT600.getMessage()]);
        RUserInfo($sex: sex, $hitHomeProviceMan: hitHomeProviceMan);
        ModelScoreResult($product600Score: product600Score);
        eval($sex == RUserInfo.SexEnum.MALE.getCode()
             && RuleUtils.lessOrEqualThan(RuleUtils.valueOfStr($product600Score),RuleUtils.getRuleParam($threshData,0))
             && (($hitHomeProviceMan != null && $hitHomeProviceMan))
             )
    then
        RuleUtils.buildHitRuleResult(BlackListTypeEnum.HOME_PROVINCE_MALE_PRODUCT600.getMessage(),
                                                        "true",
                                                        "命中居住地（省）高风险&男性&600产品模型分")
                                                        .addToResultList(ruleSetResultList);
end

rule "HOME_PROVINCE_MALE_PRODUCT600_B"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.HOME_PROVINCE_MALE_PRODUCT600.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.HOME_PROVINCE_MALE_PRODUCT600.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.HOME_PROVINCE_MALE_PRODUCT600.getMessage()]);
        RUserInfo($sex: sex, $hitHomeProviceMan: hitHomeProviceMan);
        ModelScoreResult($product600Score: product600Score);
        eval(!($sex == RUserInfo.SexEnum.MALE.getCode()
             && RuleUtils.lessOrEqualThan(RuleUtils.valueOfStr($product600Score),RuleUtils.getRuleParam($threshData,0))
             && (($hitHomeProviceMan != null && $hitHomeProviceMan))
             ))
    then
        RuleUtils.buildUnHitRuleResult(BlackListTypeEnum.HOME_PROVINCE_MALE_PRODUCT600.getMessage(),
                                                        "false",
                                                        "未命中居住地（省）高风险&男性&600产品模型分")
                                                        .addToResultList(ruleSetResultList);
end



rule "HOME_PROVINCE_FEMALE_PRODUCT600_A"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.HOME_PROVINCE_FEMALE_PRODUCT600.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.HOME_PROVINCE_FEMALE_PRODUCT600.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.HOME_PROVINCE_FEMALE_PRODUCT600.getMessage()]);
        RUserInfo($sex: sex, $hitHomeProviceFeMen: hitHomeProviceFeMen);
        ModelScoreResult($product600Score: product600Score);
        eval($sex == RUserInfo.SexEnum.FEMALE.getCode()
             && RuleUtils.lessOrEqualThan(RuleUtils.valueOfStr($product600Score),RuleUtils.getRuleParam($threshData,0))
             && (($hitHomeProviceFeMen != null && $hitHomeProviceFeMen))
             )
    then
        RuleUtils.buildHitRuleResult(BlackListTypeEnum.HOME_PROVINCE_FEMALE_PRODUCT600.getMessage(),
                                                        "true",
                                                        "命中居住地（省）高风险&女性&600产品模型分")
                                                        .addToResultList(ruleSetResultList);
end

rule "HOME_PROVINCE_FEMALE_PRODUCT600_B"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.HOME_PROVINCE_FEMALE_PRODUCT600.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.HOME_PROVINCE_FEMALE_PRODUCT600.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.HOME_PROVINCE_FEMALE_PRODUCT600.getMessage()]);
        RUserInfo($sex: sex, $hitHomeProviceFeMen: hitHomeProviceFeMen);
        ModelScoreResult($product600Score: product600Score);
        eval(!($sex == RUserInfo.SexEnum.FEMALE.getCode()
             && RuleUtils.lessOrEqualThan(RuleUtils.valueOfStr($product600Score),RuleUtils.getRuleParam($threshData,0))
             && (($hitHomeProviceFeMen != null && $hitHomeProviceFeMen))
             ))
    then
        RuleUtils.buildUnHitRuleResult(BlackListTypeEnum.HOME_PROVINCE_FEMALE_PRODUCT600.getMessage(),
                                                        "false",
                                                        "未命中居住地（省）高风险&女性&600产品模型分")
                                                        .addToResultList(ruleSetResultList);
end

