package rules.uanguang.firstborrow;


import com.yqg.drools.utils.RuleUtils;
import com.yqg.common.enums.order.BlackListTypeEnum;
import com.yqg.drools.model.base.RuleThresholdValues;
import com.yqg.drools.model.base.RuleConditionModel;
import com.yqg.drools.model.RUserInfo;
import com.yqg.drools.model.DeviceModel;
import com.yqg.drools.model.RUserInfo.SexEnum;
import com.yqg.drools.model.ShortMessage;
import com.yqg.drools.model.UserCallRecordsModel;
import com.yqg.common.utils.StringUtils;
import com.yqg.drools.model.InstalledAppInfo;
import com.yqg.drools.model.GojekModel;
import com.yqg.drools.model.FaceBookModel;
import com.yqg.drools.model.ContactInfo;
import java.util.List;
import java.util.Arrays;


global  List ruleSetResultList;



//近30天呼入占比&最早一条短信时间距申请时间的天数&近90天无通话记录总天数&女
rule "combination180626_001_A"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE.getMessage()]);
        $callRecords:UserCallRecordsModel();
        $shortMessage:ShortMessage();
        $userInfo:RUserInfo();
        eval(RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($callRecords.getRecent30InRate()),RuleUtils.getRuleParam($threshData,0))
               && RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($shortMessage.getDiffDaysForEarliestMsgAndApplyTime()),
                                             RuleUtils.getRuleParam($threshData,1))
               && RuleUtils.lessThan(RuleUtils.valueOfStr($callRecords.getRecent90NoCallDay()),
                                            RuleUtils.getRuleParam($threshData,2))
               && $userInfo.getSex()==SexEnum.FEMALE.getCode()
          );
    then
        RuleUtils.buildHitRuleResult(BlackListTypeEnum.COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE.getMessage(),
                                        "true",
                                        "命中近30天呼入占比&最早一条短信时间距申请时间的天数&近90天无通话记录总天数&女")
                                        .addToResultList(ruleSetResultList);
end

rule "combination180626_001_B"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE.getMessage()]);
        $callRecords:UserCallRecordsModel();
        $shortMessage:ShortMessage();
        $userInfo:RUserInfo();
        eval(!(RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($callRecords.getRecent30InRate()),RuleUtils.getRuleParam($threshData,0))
               && RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($shortMessage.getDiffDaysForEarliestMsgAndApplyTime()),
                                             RuleUtils.getRuleParam($threshData,1))
               && RuleUtils.lessThan(RuleUtils.valueOfStr($callRecords.getRecent90NoCallDay()),
                                            RuleUtils.getRuleParam($threshData,2))
               && $userInfo.getSex()==SexEnum.FEMALE.getCode()
          ));
    then
        RuleUtils.buildUnHitRuleResult(BlackListTypeEnum.COMB_RECENT30CALLINRATIO_DIFFOFEARLIESTMSG_NOCALLDAYS_FEMALE.getMessage(),
                                        "false",
                                        "未命中近30天呼入占比&最早一条短信时间距申请时间的天数&近90天无通话记录总天数&女")
                                        .addToResultList(ruleSetResultList);
end

//近90天打入通话次数&最早一条短信时间距申请时间的天数&学历&女
rule "combination180626_002_A"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE.getMessage()]);
        $callRecords:UserCallRecordsModel();
        $shortMessage:ShortMessage();
        $userInfo:RUserInfo();
        eval(RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($callRecords.getRecent90InCount()),RuleUtils.getRuleParam($threshData,0))
               && RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($shortMessage.getDiffDaysForEarliestMsgAndApplyTime()),
                                             RuleUtils.getRuleParam($threshData,1))
               &&RuleUtils.containsString(Arrays.asList("Diploma","Sarjana","Pascasarjana","Doktor"),$userInfo.getAcademic())
               && $userInfo.getSex()==SexEnum.FEMALE.getCode()
          );
    then
        RuleUtils.buildHitRuleResult(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE.getMessage(),
                                        "true",
                                        "命中近90天打入通话次数&最早一条短信时间距申请时间的天数&学历&女")
                                        .addToResultList(ruleSetResultList);
end

rule "combination180626_002_B"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE.getMessage()))
    when
       RuleConditionModel(isSuitableForRule(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE.getMessage()));
       $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE.getMessage()]);
       $callRecords:UserCallRecordsModel();
       $shortMessage:ShortMessage();
       $userInfo:RUserInfo();
       eval(!(RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($callRecords.getRecent90InCount()),RuleUtils.getRuleParam($threshData,0))
              && RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($shortMessage.getDiffDaysForEarliestMsgAndApplyTime()),
                                            RuleUtils.getRuleParam($threshData,1))
              &&RuleUtils.containsString(Arrays.asList("Diploma","Sarjana","Pascasarjana","Doktor"),$userInfo.getAcademic())
              && $userInfo.getSex()==SexEnum.FEMALE.getCode()
         ));
    then
        RuleUtils.buildUnHitRuleResult(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_DIFFOFEARLIESTMSG_EDUCATION_FEMALE.getMessage(),
                                        "false",
                                        "未命中近90天打入通话次数&最早一条短信时间距申请时间的天数&学历&女")
                                        .addToResultList(ruleSetResultList);
end

//手机使用时长（单位：天）&最早一条短信时间距申请时间的天数&孩子数量&女
rule "combination180626_003_A"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE.getMessage()]);
        $callRecords:UserCallRecordsModel();
        $shortMessage:ShortMessage();
        $userInfo:RUserInfo();
        eval(RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($callRecords.getDiffTime()),RuleUtils.getRuleParam($threshData,0))
               && RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($shortMessage.getDiffDaysForEarliestMsgAndApplyTime()),
                                             RuleUtils.getRuleParam($threshData,1))
               &&RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($userInfo.getChildrenAmount()),
                                            RuleUtils.getRuleParam($threshData,2))
               &&RuleUtils.lessOrEqualThan(RuleUtils.valueOfStr($userInfo.getChildrenAmount()),
                                            RuleUtils.getRuleParam($threshData,3))
               && $userInfo.getSex()==SexEnum.FEMALE.getCode()
          );
    then
        RuleUtils.buildHitRuleResult(BlackListTypeEnum.COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE.getMessage(),
                                        "true",
                                        "命中手机使用时长（单位：天）&最早一条短信时间距申请时间的天数&孩子数量&女")
                                        .addToResultList(ruleSetResultList);
end

rule "combination180626_003_B"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE.getMessage()))
    when
      RuleConditionModel(isSuitableForRule(BlackListTypeEnum.COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE.getMessage()));
      $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE.getMessage()]);
      $callRecords:UserCallRecordsModel();
      $shortMessage:ShortMessage();
      $userInfo:RUserInfo();
      eval(!(RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($callRecords.getDiffTime()),RuleUtils.getRuleParam($threshData,0))
             && RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($shortMessage.getDiffDaysForEarliestMsgAndApplyTime()),
                                           RuleUtils.getRuleParam($threshData,1))
             &&RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($userInfo.getChildrenAmount()),
                                          RuleUtils.getRuleParam($threshData,2))
             &&RuleUtils.lessOrEqualThan(RuleUtils.valueOfStr($userInfo.getChildrenAmount()),
                                          RuleUtils.getRuleParam($threshData,3))
             && $userInfo.getSex()==SexEnum.FEMALE.getCode()
        ));
    then
        RuleUtils.buildUnHitRuleResult(BlackListTypeEnum.COMB_MOBILEUSAGETIMES_DIFFOFEARLIESTMSG_CHILDRENCOUNT_FEMALE.getMessage(),
                                        "false",
                                        "未命中手机使用时长（单位：天）&最早一条短信时间距申请时间的天数&孩子数量&女")
                                        .addToResultList(ruleSetResultList);
end



//近90天打入通话次数&近90天无通话记录总天数&学历&男
rule "combination180626_004_A"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE.getMessage()))
    when
        RuleConditionModel(isSuitableForRule(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE.getMessage()));
        $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE.getMessage()]);
        $callRecords:UserCallRecordsModel();
        $userInfo:RUserInfo();
        eval(RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($callRecords.getRecent90InCount()),RuleUtils.getRuleParam($threshData,0))
               && RuleUtils.lessThan(RuleUtils.valueOfStr($callRecords.getRecent90NoCallDay()),
                                             RuleUtils.getRuleParam($threshData,1))
               &&RuleUtils.containsString(Arrays.asList("Diploma","Sarjana","Pascasarjana","Doktor"),$userInfo.getAcademic())
               && $userInfo.getSex()==SexEnum.MALE.getCode()
          );
    then
        RuleUtils.buildHitRuleResult(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE.getMessage(),
                                        "true",
                                        "命中近90天打入通话次数&近90天无通话记录总天数&学历&男")
                                        .addToResultList(ruleSetResultList);
end

rule "combination180626_004_B"
    salience($thresholdValues.getRuleOrder(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE.getMessage()))
    when
      RuleConditionModel(isSuitableForRule(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE.getMessage()));
      $thresholdValues:RuleThresholdValues($threshData:thresholdMap[BlackListTypeEnum.COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE.getMessage()]);
      $callRecords:UserCallRecordsModel();
      $userInfo:RUserInfo();
      eval(!(RuleUtils.greatOrEqualThan(RuleUtils.valueOfStr($callRecords.getRecent90InCount()),RuleUtils.getRuleParam($threshData,0))
             && RuleUtils.lessThan(RuleUtils.valueOfStr($callRecords.getRecent90NoCallDay()),
                                           RuleUtils.getRuleParam($threshData,1))
             &&RuleUtils.containsString(Arrays.asList("Diploma","Sarjana","Pascasarjana","Doktor"),$userInfo.getAcademic())
             && $userInfo.getSex()==SexEnum.MALE.getCode()
        ));
    then
        RuleUtils.buildUnHitRuleResult(BlackListTypeEnum.COMB_RECENT90CALLINTIMES_NOCALLDAYS_EDUCATION_MALE.getMessage(),
                                        "false",
                                        "未命中近90天打入通话次数&近90天无通话记录总天数&学历&男")
                                        .addToResultList(ruleSetResultList);
end

